from django.urls import path

from .views import (
    CustomerReturnCreateView,
    CustomerReturnExportView,
    CustomerReturnImportTemplateView,
    CustomerReturnImportView,
    CustomerReturnListView,
    CustomerReturnDetailView,
    CustomerReturnConfirmReceiptView,
    CustomerReturnPrintView,
    CustomerReturnUpdateView,
    CustomerReturnVoidView,
    SalesOrderConfirmView,
    SalesOrderCreateView,
    SalesOrderCreateShipmentView,
    SalesOrderDetailView,
    SalesOrderUpdateView,
    SalesOrderExportView,
    SalesOrderImportTemplateView,
    SalesOrderImportView,
    SalesOrderListView,
    SalesOrderPrintView,
    SalesOrderRecheckShortageView,
    SalesOrderSubmitView,
    SalesOrderVoidView,
    SalesShipmentConfirmView,
    SalesShipmentDetailView,
    SalesShipmentExportView,
    SalesShipmentImportTemplateView,
    SalesShipmentImportView,
    SalesShipmentListView,
    SalesShipmentPrintView,
    SalesShipmentUpdateView,
    SalesShipmentVoidView,
    SampleLoanDetailView,
    SampleLoanCreateView,
    SampleLoanConfirmOutView,
    SampleLoanConvertToSalesView,
    SampleLoanExportView,
    SampleLoanImportTemplateView,
    SampleLoanImportView,
    SampleLoanItemCreateView,
    SampleLoanListView,
    SampleLoanPrintView,
    SampleLoanReturnConfirmView,
    SampleLoanReturnCreateView,
    SampleLoanReturnDetailView,
    SampleLoanReturnExportView,
    SampleLoanReturnListView,
    SampleLoanReturnPrintView,
    SampleLoanReturnUpdateView,
    SampleLoanReturnVoidView,
    ShortageCreatePurchaseRequestView,
    ShortageAlertListView,
    ShortageAlertExportView,
)

app_name = "sales"

urlpatterns = [
    path("orders/", SalesOrderListView.as_view(), name="sales_order_list"),
    path("orders/export/", SalesOrderExportView.as_view(), name="sales_order_export"),
    path("orders/import-template/", SalesOrderImportTemplateView.as_view(), name="sales_order_import_template"),
    path("orders/import/", SalesOrderImportView.as_view(), name="sales_order_import"),
    path("orders/new/", SalesOrderCreateView.as_view(), name="sales_order_create"),
    path("orders/<int:pk>/", SalesOrderDetailView.as_view(), name="sales_order_detail"),
    path("orders/<int:pk>/edit/", SalesOrderUpdateView.as_view(), name="sales_order_edit"),
    path("orders/<int:pk>/print/", SalesOrderPrintView.as_view(), name="sales_order_print"),
    path("orders/<int:pk>/submit/", SalesOrderSubmitView.as_view(), name="sales_order_submit"),
    path("orders/<int:pk>/confirm/", SalesOrderConfirmView.as_view(), name="sales_order_confirm"),
    path("orders/<int:pk>/recheck-shortage/", SalesOrderRecheckShortageView.as_view(), name="sales_order_recheck_shortage"),
    path("orders/<int:pk>/void/", SalesOrderVoidView.as_view(), name="sales_order_void"),
    path("orders/<int:pk>/create-shipment/", SalesOrderCreateShipmentView.as_view(), name="sales_order_create_shipment"),
    path("shortages/", ShortageAlertListView.as_view(), name="shortage_alert_list"),
    path("shortages/export/", ShortageAlertExportView.as_view(), name="shortage_alert_export"),
    path("shortages/create-purchase-request/", ShortageCreatePurchaseRequestView.as_view(), name="shortage_create_purchase_request"),
    path("shipments/", SalesShipmentListView.as_view(), name="sales_shipment_list"),
    path("shipments/export/", SalesShipmentExportView.as_view(), name="sales_shipment_export"),
    path("shipments/import-template/", SalesShipmentImportTemplateView.as_view(), name="sales_shipment_import_template"),
    path("shipments/import/", SalesShipmentImportView.as_view(), name="sales_shipment_import"),
    path("shipments/<int:pk>/", SalesShipmentDetailView.as_view(), name="sales_shipment_detail"),
    path("shipments/<int:pk>/edit/", SalesShipmentUpdateView.as_view(), name="sales_shipment_edit"),
    path("shipments/<int:pk>/void/", SalesShipmentVoidView.as_view(), name="sales_shipment_void"),
    path("shipments/<int:pk>/print/", SalesShipmentPrintView.as_view(), name="sales_shipment_print"),
    path("shipments/<int:pk>/confirm/", SalesShipmentConfirmView.as_view(), name="sales_shipment_confirm"),
    path("returns/", CustomerReturnListView.as_view(), name="customer_return_list"),
    path("returns/export/", CustomerReturnExportView.as_view(), name="customer_return_export"),
    path("returns/import-template/", CustomerReturnImportTemplateView.as_view(), name="customer_return_import_template"),
    path("returns/import/", CustomerReturnImportView.as_view(), name="customer_return_import"),
    path("returns/new/", CustomerReturnCreateView.as_view(), name="customer_return_create"),
    path("returns/<int:pk>/", CustomerReturnDetailView.as_view(), name="customer_return_detail"),
    path("returns/<int:pk>/edit/", CustomerReturnUpdateView.as_view(), name="customer_return_edit"),
    path("returns/<int:pk>/print/", CustomerReturnPrintView.as_view(), name="customer_return_print"),
    path("returns/<int:pk>/void/", CustomerReturnVoidView.as_view(), name="customer_return_void"),
    path("returns/<int:pk>/confirm-receipt/", CustomerReturnConfirmReceiptView.as_view(), name="customer_return_confirm_receipt"),
    path("sample-loans/", SampleLoanListView.as_view(), name="sample_loan_list"),
    path("sample-loans/export/", SampleLoanExportView.as_view(), name="sample_loan_export"),
    path("sample-loans/import-template/", SampleLoanImportTemplateView.as_view(), name="sample_loan_import_template"),
    path("sample-loans/import/", SampleLoanImportView.as_view(), name="sample_loan_import"),
    path("sample-loans/new/", SampleLoanCreateView.as_view(), name="sample_loan_create"),
    path("sample-loans/<int:pk>/", SampleLoanDetailView.as_view(), name="sample_loan_detail"),
    path("sample-loans/<int:pk>/print/", SampleLoanPrintView.as_view(), name="sample_loan_print"),
    path("sample-loans/<int:pk>/items/new/", SampleLoanItemCreateView.as_view(), name="sample_loan_item_create"),
    path("sample-loans/<int:pk>/confirm-out/", SampleLoanConfirmOutView.as_view(), name="sample_loan_confirm_out"),
    path("sample-loans/<int:pk>/convert-to-sales/", SampleLoanConvertToSalesView.as_view(), name="sample_loan_convert_to_sales"),
    path("sample-loans/<int:pk>/returns/new/", SampleLoanReturnCreateView.as_view(), name="sample_loan_return_create"),
    path("sample-returns/", SampleLoanReturnListView.as_view(), name="sample_loan_return_list"),
    path("sample-returns/export/", SampleLoanReturnExportView.as_view(), name="sample_loan_return_export"),
    path("sample-returns/<int:pk>/", SampleLoanReturnDetailView.as_view(), name="sample_loan_return_detail"),
    path("sample-returns/<int:pk>/edit/", SampleLoanReturnUpdateView.as_view(), name="sample_loan_return_edit"),
    path("sample-returns/<int:pk>/print/", SampleLoanReturnPrintView.as_view(), name="sample_loan_return_print"),
    path("sample-returns/<int:pk>/void/", SampleLoanReturnVoidView.as_view(), name="sample_loan_return_void"),
    path("sample-returns/<int:pk>/confirm/", SampleLoanReturnConfirmView.as_view(), name="sample_loan_return_confirm"),
]
