# Generated by Django 6.0.6 on 2026-06-08 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_no', models.CharField(max_length=100, unique=True)),
                ('backup_type', models.CharField(max_length=40)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'backups',
            },
        ),
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=24)),
                ('sequence_date', models.DateField()),
                ('current_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'document_sequences',
                'constraints': [models.UniqueConstraint(fields=('prefix', 'sequence_date'), name='uq_document_sequence_prefix_date')],
            },
        ),
        migrations.CreateModel(
            name='PendingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('running', '处理中'), ('success', '成功'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=16)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pending_events',
                'indexes': [models.Index(fields=['status', 'event_type', 'next_retry_at'], name='pending_eve_status_788625_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReleaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.CharField(max_length=80, unique=True)),
                ('released_at', models.DateTimeField()),
                ('summary', models.TextField(blank=True)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'release_records',
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_key', models.CharField(max_length=120, unique=True)),
                ('setting_value', models.TextField(blank=True)),
                ('value_type', models.CharField(default='string', max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_settings',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_no', models.CharField(max_length=100, unique=True)),
                ('action', models.CharField(max_length=100)),
                ('source_doc_type', models.CharField(max_length=80)),
                ('source_doc_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('source_doc_no', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('before_snapshot', models.JSONField(blank=True, default=dict)),
                ('after_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'indexes': [models.Index(fields=['operator', 'created_at'], name='audit_logs_operato_9e4002_idx'), models.Index(fields=['source_doc_type', 'source_doc_id'], name='audit_logs_source__8247b6_idx'), models.Index(fields=['action', 'created_at'], name='audit_logs_action_391715_idx')],
            },
        ),
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.CharField(max_length=100, unique=True)),
                ('job_type', models.CharField(max_length=80)),
                ('trigger_type', models.CharField(blank=True, max_length=40)),
                ('input_params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '运行中'), ('success', '成功'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'background_jobs',
                'indexes': [models.Index(fields=['job_type', 'status'], name='background__job_typ_0be1ba_idx'), models.Index(fields=['status', 'created_at'], name='background__status_2e8f1f_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=80)),
                ('filter_name', models.CharField(max_length=120)),
                ('filter_json', models.JSONField(default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_filters',
                'constraints': [models.UniqueConstraint(fields=('user', 'module', 'filter_name'), name='uq_saved_filter_name')],
            },
        ),
    ]
