from django.urls import path

from .views import (
    PurchaseOrderCreateView,
    PurchaseOrderCreateReceiptView,
    PurchaseOrderDetailView,
    PurchaseOrderUpdateView,
    PurchaseOrderExportView,
    PurchaseOrderImportTemplateView,
    PurchaseOrderImportView,
    PurchaseOrderItemCreateView,
    PurchaseOrderListView,
    PurchaseOrderPrintView,
    PurchaseOrderVoidView,
    PurchaseReceiptConfirmView,
    PurchaseReceiptDetailView,
    PurchaseReceiptExportView,
    PurchaseReceiptImportTemplateView,
    PurchaseReceiptImportView,
    PurchaseReceiptListView,
    PurchaseReceiptPrintView,
    PurchaseReceiptUpdateView,
    PurchaseRequestCreateOrderView,
    PurchaseRequestCreateView,
    PurchaseRequestDetailView,
    PurchaseRequestExportView,
    PurchaseRequestImportTemplateView,
    PurchaseRequestImportView,
    PurchaseRequestListView,
    PurchaseRequestUpdateView,
    PurchaseRequestVoidView,
    SupplierReturnConfirmOutView,
    SupplierReturnCreateView,
    SupplierReturnDetailView,
    SupplierReturnExportView,
    SupplierReturnImportTemplateView,
    SupplierReturnImportView,
    SupplierReturnListView,
    SupplierReturnPrintView,
    SupplierReturnReceiptItemsView,
    SupplierReturnUpdateView,
    SupplierReturnVoidView,
)

app_name = "purchase"

urlpatterns = [
    path("requests/", PurchaseRequestListView.as_view(), name="purchase_request_list"),
    path("requests/export/", PurchaseRequestExportView.as_view(), name="purchase_request_export"),
    path("requests/import-template/", PurchaseRequestImportTemplateView.as_view(), name="purchase_request_import_template"),
    path("requests/import/", PurchaseRequestImportView.as_view(), name="purchase_request_import"),
    path("requests/new/", PurchaseRequestCreateView.as_view(), name="purchase_request_create"),
    path("requests/<int:pk>/", PurchaseRequestDetailView.as_view(), name="purchase_request_detail"),
    path("requests/<int:pk>/edit/", PurchaseRequestUpdateView.as_view(), name="purchase_request_edit"),
    path("requests/<int:pk>/void/", PurchaseRequestVoidView.as_view(), name="purchase_request_void"),
    path("requests/<int:pk>/create-order/", PurchaseRequestCreateOrderView.as_view(), name="purchase_request_create_order"),
    path("orders/", PurchaseOrderListView.as_view(), name="purchase_order_list"),
    path("orders/export/", PurchaseOrderExportView.as_view(), name="purchase_order_export"),
    path("orders/import-template/", PurchaseOrderImportTemplateView.as_view(), name="purchase_order_import_template"),
    path("orders/import/", PurchaseOrderImportView.as_view(), name="purchase_order_import"),
    path("orders/new/", PurchaseOrderCreateView.as_view(), name="purchase_order_create"),
    path("orders/<int:pk>/", PurchaseOrderDetailView.as_view(), name="purchase_order_detail"),
    path("orders/<int:pk>/edit/", PurchaseOrderUpdateView.as_view(), name="purchase_order_edit"),
    path("orders/<int:pk>/print/", PurchaseOrderPrintView.as_view(), name="purchase_order_print"),
    path("orders/<int:pk>/void/", PurchaseOrderVoidView.as_view(), name="purchase_order_void"),
    path("orders/<int:pk>/create-receipt/", PurchaseOrderCreateReceiptView.as_view(), name="purchase_order_create_receipt"),
    path("orders/<int:pk>/items/new/", PurchaseOrderItemCreateView.as_view(), name="purchase_order_item_create"),
    path("receipts/", PurchaseReceiptListView.as_view(), name="purchase_receipt_list"),
    path("receipts/export/", PurchaseReceiptExportView.as_view(), name="purchase_receipt_export"),
    path("receipts/import-template/", PurchaseReceiptImportTemplateView.as_view(), name="purchase_receipt_import_template"),
    path("receipts/import/", PurchaseReceiptImportView.as_view(), name="purchase_receipt_import"),
    path("receipts/<int:pk>/", PurchaseReceiptDetailView.as_view(), name="purchase_receipt_detail"),
    path("receipts/<int:pk>/edit/", PurchaseReceiptUpdateView.as_view(), name="purchase_receipt_edit"),
    path("receipts/<int:pk>/print/", PurchaseReceiptPrintView.as_view(), name="purchase_receipt_print"),
    path("receipts/<int:pk>/confirm/", PurchaseReceiptConfirmView.as_view(), name="purchase_receipt_confirm"),
    path("supplier-returns/", SupplierReturnListView.as_view(), name="supplier_return_list"),
    path("supplier-returns/export/", SupplierReturnExportView.as_view(), name="supplier_return_export"),
    path("supplier-returns/import-template/", SupplierReturnImportTemplateView.as_view(), name="supplier_return_import_template"),
    path("supplier-returns/import/", SupplierReturnImportView.as_view(), name="supplier_return_import"),
    path("supplier-returns/receipt-items/", SupplierReturnReceiptItemsView.as_view(), name="supplier_return_receipt_items"),
    path("supplier-returns/new/", SupplierReturnCreateView.as_view(), name="supplier_return_create"),
    path("supplier-returns/<int:pk>/", SupplierReturnDetailView.as_view(), name="supplier_return_detail"),
    path("supplier-returns/<int:pk>/edit/", SupplierReturnUpdateView.as_view(), name="supplier_return_edit"),
    path("supplier-returns/<int:pk>/print/", SupplierReturnPrintView.as_view(), name="supplier_return_print"),
    path("supplier-returns/<int:pk>/void/", SupplierReturnVoidView.as_view(), name="supplier_return_void"),
    path("supplier-returns/<int:pk>/confirm-out/", SupplierReturnConfirmOutView.as_view(), name="supplier_return_confirm_out"),
]
