# Generated by Django 6.0.6 on 2026-06-08 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
        ('purchase', '0002_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCreditBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_doc_type', models.CharField(max_length=80)),
                ('source_doc_id', models.PositiveBigIntegerField()),
                ('source_doc_no', models.CharField(blank=True, max_length=100)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('used_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('to_advance', '已转预收'), ('part_used', '部分使用'), ('used_up', '已用完'), ('refunded', '已退款'), ('closed', '已关闭')], default='pending', max_length=24)),
                ('process_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_balances', to='masterdata.customer')),
            ],
            options={
                'db_table': 'customer_credit_balances',
            },
        ),
        migrations.CreateModel(
            name='CustomerCreditBalanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(max_length=100, unique=True)),
                ('action_type', models.CharField(choices=[('to_advance', '转预收款'), ('allocate_to_order', '核销其他订单'), ('refund', '登记退款'), ('close', '关闭')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('target_doc_type', models.CharField(blank=True, max_length=80)),
                ('target_doc_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('target_doc_no', models.CharField(blank=True, max_length=100)),
                ('idempotency_key', models.CharField(max_length=200)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('credit_balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.customercreditbalance')),
            ],
            options={
                'db_table': 'customer_credit_balance_transactions',
            },
        ),
        migrations.CreateModel(
            name='CustomerReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(max_length=100, unique=True)),
                ('receipt_date', models.DateField()),
                ('receipt_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unallocated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('receipt_method', models.CharField(choices=[('cash', '现金'), ('transfer', '转账'), ('check', '支票'), ('other', '其他')], default='transfer', max_length=24)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_approval', '待审核'), ('confirmed', '已确认'), ('voided', '已作废'), ('reversed', '已红冲'), ('part_reversed', '部分红冲')], default='draft', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('remark', models.TextField(blank=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='masterdata.customer')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handled_customer_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_receipts',
            },
        ),
        migrations.CreateModel(
            name='CustomerReceiptReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reversal_no', models.CharField(max_length=100, unique=True)),
                ('reversal_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_approval', '待审核'), ('confirmed', '已确认'), ('voided', '已作废')], default='draft', max_length=32)),
                ('idempotency_key', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('source_receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='finance.customerreceipt')),
            ],
            options={
                'db_table': 'customer_receipt_reversals',
            },
        ),
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconciliation_no', models.CharField(max_length=100, unique=True)),
                ('party_type', models.CharField(choices=[('customer', '客户'), ('supplier', '供应商')], max_length=24)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('voided', '已作废')], default='draft', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.customer')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.supplier')),
            ],
            options={
                'db_table': 'reconciliations',
            },
        ),
        migrations.CreateModel(
            name='CustomerReceiptAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('allocation_type', models.CharField(choices=[('sales_order', '销售订单核销'), ('reconciliation', '客户对账单核销'), ('reversal', '红冲反向核销'), ('credit_balance', '余额核销')], default='sales_order', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.customerreceipt')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.salesorder')),
                ('source_reversal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reverse_allocations', to='finance.customerreceiptreversal')),
                ('reconciliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.reconciliation')),
            ],
            options={
                'db_table': 'customer_receipt_allocations',
            },
        ),
        migrations.CreateModel(
            name='SupplierCreditBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_doc_type', models.CharField(max_length=80)),
                ('source_doc_id', models.PositiveBigIntegerField()),
                ('source_doc_no', models.CharField(blank=True, max_length=100)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('used_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('to_advance', '已转预付'), ('part_used', '部分使用'), ('used_up', '已用完'), ('refunded', '已退款'), ('closed', '已关闭')], default='pending', max_length=24)),
                ('process_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_balances', to='masterdata.supplier')),
            ],
            options={
                'db_table': 'supplier_credit_balances',
            },
        ),
        migrations.CreateModel(
            name='SupplierCreditBalanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(max_length=100, unique=True)),
                ('action_type', models.CharField(choices=[('to_advance', '转预付款'), ('allocate_to_receipt', '核销其他进货单'), ('refund', '登记供应商退款'), ('close', '关闭')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('target_doc_type', models.CharField(blank=True, max_length=80)),
                ('target_doc_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('target_doc_no', models.CharField(blank=True, max_length=100)),
                ('idempotency_key', models.CharField(max_length=200)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('credit_balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.suppliercreditbalance')),
            ],
            options={
                'db_table': 'supplier_credit_balance_transactions',
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_no', models.CharField(max_length=100, unique=True)),
                ('payment_date', models.DateField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unallocated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payment_method', models.CharField(choices=[('cash', '现金'), ('transfer', '转账'), ('check', '支票'), ('other', '其他')], default='transfer', max_length=24)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_approval', '待审核'), ('confirmed', '已确认'), ('voided', '已作废'), ('reversed', '已红冲'), ('part_reversed', '部分红冲')], default='draft', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('remark', models.TextField(blank=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handled_supplier_payments', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='masterdata.supplier')),
            ],
            options={
                'db_table': 'supplier_payments',
            },
        ),
        migrations.CreateModel(
            name='SupplierPaymentReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reversal_no', models.CharField(max_length=100, unique=True)),
                ('reversal_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_approval', '待审核'), ('confirmed', '已确认'), ('voided', '已作废')], default='draft', max_length=32)),
                ('idempotency_key', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('source_payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='finance.supplierpayment')),
            ],
            options={
                'db_table': 'supplier_payment_reversals',
            },
        ),
        migrations.CreateModel(
            name='SupplierPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('allocation_type', models.CharField(choices=[('purchase_receipt', '进货单核销'), ('reconciliation', '供应商对账单核销'), ('reversal', '红冲反向核销'), ('credit_balance', '余额核销')], default='purchase_receipt', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('purchase_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchase.purchasereceipt')),
                ('reconciliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.reconciliation')),
                ('supplier_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.supplierpayment')),
                ('source_reversal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reverse_allocations', to='finance.supplierpaymentreversal')),
            ],
            options={
                'db_table': 'supplier_payment_allocations',
            },
        ),
        migrations.AddIndex(
            model_name='customercreditbalance',
            index=models.Index(fields=['customer', 'status', 'remaining_amount'], name='customer_cr_custome_db68f9_idx'),
        ),
        migrations.AddIndex(
            model_name='customercreditbalance',
            index=models.Index(fields=['source_doc_type', 'source_doc_id'], name='customer_cr_source__6f1b2f_idx'),
        ),
        migrations.AddIndex(
            model_name='customercreditbalancetransaction',
            index=models.Index(fields=['credit_balance', 'action_type'], name='customer_cr_credit__46448f_idx'),
        ),
        migrations.AddIndex(
            model_name='customercreditbalancetransaction',
            index=models.Index(fields=['target_doc_type', 'target_doc_id'], name='customer_cr_target__494f94_idx'),
        ),
        migrations.AddConstraint(
            model_name='customercreditbalancetransaction',
            constraint=models.UniqueConstraint(fields=('credit_balance', 'idempotency_key'), name='uq_customer_credit_txn_idem'),
        ),
        migrations.AddIndex(
            model_name='customerreceipt',
            index=models.Index(fields=['customer', 'status', 'receipt_date'], name='customer_re_custome_3e5d82_idx'),
        ),
        migrations.AddIndex(
            model_name='customerreceipt',
            index=models.Index(fields=['status', 'created_at'], name='customer_re_status_ba5b77_idx'),
        ),
        migrations.AddIndex(
            model_name='customerreceiptreversal',
            index=models.Index(fields=['source_receipt', 'status'], name='customer_re_source__8d22ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerreceiptreversal',
            constraint=models.UniqueConstraint(fields=('source_receipt', 'idempotency_key'), name='uq_customer_receipt_reversal_idem'),
        ),
        migrations.AddIndex(
            model_name='reconciliation',
            index=models.Index(fields=['party_type', 'status'], name='reconciliat_party_t_311ec9_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliation',
            index=models.Index(fields=['customer', 'status'], name='reconciliat_custome_f12792_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliation',
            index=models.Index(fields=['supplier', 'status'], name='reconciliat_supplie_6e1e6f_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliation',
            index=models.Index(fields=['period_start', 'period_end'], name='reconciliat_period__f995c1_idx'),
        ),
        migrations.AddIndex(
            model_name='customerreceiptallocation',
            index=models.Index(fields=['customer_receipt', 'allocation_type'], name='customer_re_custome_dad6a0_idx'),
        ),
        migrations.AddIndex(
            model_name='customerreceiptallocation',
            index=models.Index(fields=['sales_order'], name='customer_re_sales_o_9661fc_idx'),
        ),
        migrations.AddIndex(
            model_name='customerreceiptallocation',
            index=models.Index(fields=['reconciliation'], name='customer_re_reconci_65ba62_idx'),
        ),
        migrations.AddIndex(
            model_name='suppliercreditbalance',
            index=models.Index(fields=['supplier', 'status', 'remaining_amount'], name='supplier_cr_supplie_ccb9f5_idx'),
        ),
        migrations.AddIndex(
            model_name='suppliercreditbalance',
            index=models.Index(fields=['source_doc_type', 'source_doc_id'], name='supplier_cr_source__20ee2b_idx'),
        ),
        migrations.AddIndex(
            model_name='suppliercreditbalancetransaction',
            index=models.Index(fields=['credit_balance', 'action_type'], name='supplier_cr_credit__cbe61a_idx'),
        ),
        migrations.AddIndex(
            model_name='suppliercreditbalancetransaction',
            index=models.Index(fields=['target_doc_type', 'target_doc_id'], name='supplier_cr_target__55e901_idx'),
        ),
        migrations.AddConstraint(
            model_name='suppliercreditbalancetransaction',
            constraint=models.UniqueConstraint(fields=('credit_balance', 'idempotency_key'), name='uq_supplier_credit_txn_idem'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['supplier', 'status', 'payment_date'], name='supplier_pa_supplie_663983_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['status', 'created_at'], name='supplier_pa_status_057b86_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpaymentreversal',
            index=models.Index(fields=['source_payment', 'status'], name='supplier_pa_source__91f994_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierpaymentreversal',
            constraint=models.UniqueConstraint(fields=('source_payment', 'idempotency_key'), name='uq_supplier_payment_reversal_idem'),
        ),
        migrations.AddIndex(
            model_name='supplierpaymentallocation',
            index=models.Index(fields=['supplier_payment', 'allocation_type'], name='supplier_pa_supplie_c751c0_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpaymentallocation',
            index=models.Index(fields=['purchase_receipt'], name='supplier_pa_purchas_0e2ab0_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpaymentallocation',
            index=models.Index(fields=['reconciliation'], name='supplier_pa_reconci_71bcae_idx'),
        ),
    ]
