# Generated by Django 6.0.6 on 2026-06-09 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('source_type', models.CharField(choices=[('sales_order', '销售订单'), ('purchase_receipt', '进货单')], max_length=32)),
                ('source_doc_id', models.PositiveBigIntegerField()),
                ('source_no', models.CharField(max_length=100)),
                ('source_date', models.DateField()),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('adjust_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('open_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.reconciliation')),
            ],
            options={
                'db_table': 'reconciliation_items',
                'indexes': [models.Index(fields=['reconciliation', 'line_no'], name='reconciliat_reconci_787d14_idx'), models.Index(fields=['source_type', 'source_doc_id'], name='reconciliat_source__3d52f4_idx')],
                'constraints': [models.UniqueConstraint(fields=('reconciliation', 'line_no'), name='uq_reconciliation_item_line'), models.UniqueConstraint(fields=('reconciliation', 'source_type', 'source_doc_id'), name='uq_reconciliation_item_source')],
            },
        ),
    ]
