# Generated by Django 6.0.6 on 2026-06-26 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_reconciliationitem'),
        ('masterdata', '0002_customeraddress_address_type_and_more'),
        ('purchase', '0002_initial'),
        ('sales', '0003_salesorder_customer_contract_no_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_no', models.CharField(max_length=100, unique=True)),
                ('source_doc_no', models.CharField(blank=True, max_length=100)),
                ('opening_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('opening_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('settled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('open', '未结清'), ('part_settled', '部分结清'), ('settled', '已结清'), ('voided', '已作废')], default='open', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'opening_receivables',
            },
        ),
        migrations.AlterField(
            model_name='customerreceiptallocation',
            name='allocation_type',
            field=models.CharField(choices=[('sales_order', '销售订单核销'), ('reconciliation', '客户对账单核销'), ('opening_receivable', '期初应收核销'), ('reversal', '红冲反向核销'), ('credit_balance', '余额核销')], default='sales_order', max_length=32),
        ),
        migrations.AlterField(
            model_name='supplierpaymentallocation',
            name='allocation_type',
            field=models.CharField(choices=[('purchase_receipt', '进货单核销'), ('reconciliation', '供应商对账单核销'), ('opening_payable', '期初应付核销'), ('reversal', '红冲反向核销'), ('credit_balance', '余额核销')], default='purchase_receipt', max_length=32),
        ),
        migrations.CreateModel(
            name='ExpenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_no', models.CharField(max_length=100, unique=True)),
                ('expense_date', models.DateField()),
                ('category', models.CharField(choices=[('auxiliary', '采购辅料'), ('freight', '运费'), ('electricity', '电费'), ('rent', '房租'), ('equipment', '设备采购'), ('meal', '餐费'), ('business', '业务费用'), ('gift', '礼品'), ('office', '办公费用'), ('other', '其他')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_method', models.CharField(choices=[('cash', '现金'), ('transfer', '转账'), ('check', '支票'), ('other', '其他')], default='transfer', max_length=24)),
                ('payee', models.CharField(blank=True, max_length=160)),
                ('invoice_no', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('voided', '已作废')], default='draft', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('remark', models.TextField(blank=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handled_expense_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'expense_records',
            },
        ),
        migrations.CreateModel(
            name='OpeningPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_no', models.CharField(max_length=100, unique=True)),
                ('source_doc_no', models.CharField(blank=True, max_length=100)),
                ('opening_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('opening_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('settled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('open', '未结清'), ('part_settled', '部分结清'), ('settled', '已结清'), ('voided', '已作废')], default='open', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_payables', to='masterdata.supplier')),
            ],
            options={
                'db_table': 'opening_payables',
            },
        ),
        migrations.AddField(
            model_name='supplierpaymentallocation',
            name='opening_payable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.openingpayable'),
        ),
        migrations.AddIndex(
            model_name='supplierpaymentallocation',
            index=models.Index(fields=['opening_payable'], name='supplier_pa_opening_d38832_idx'),
        ),
        migrations.AddField(
            model_name='openingreceivable',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='openingreceivable',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_receivables', to='masterdata.customer'),
        ),
        migrations.AddField(
            model_name='customerreceiptallocation',
            name='opening_receivable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.openingreceivable'),
        ),
        migrations.AddIndex(
            model_name='customerreceiptallocation',
            index=models.Index(fields=['opening_receivable'], name='customer_re_opening_624974_idx'),
        ),
        migrations.AddIndex(
            model_name='expenserecord',
            index=models.Index(fields=['expense_date', 'category'], name='expense_rec_expense_c23175_idx'),
        ),
        migrations.AddIndex(
            model_name='expenserecord',
            index=models.Index(fields=['status', 'created_at'], name='expense_rec_status_610df6_idx'),
        ),
        migrations.AddIndex(
            model_name='openingpayable',
            index=models.Index(fields=['supplier', 'status', 'opening_date'], name='opening_pay_supplie_adde0b_idx'),
        ),
        migrations.AddIndex(
            model_name='openingpayable',
            index=models.Index(fields=['status', 'remaining_amount'], name='opening_pay_status_06f710_idx'),
        ),
        migrations.AddIndex(
            model_name='openingreceivable',
            index=models.Index(fields=['customer', 'status', 'opening_date'], name='opening_rec_custome_d14995_idx'),
        ),
        migrations.AddIndex(
            model_name='openingreceivable',
            index=models.Index(fields=['status', 'remaining_amount'], name='opening_rec_status_bdcc27_idx'),
        ),
    ]
