# Generated by Django 6.0.6 on 2026-07-12 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_openingreceivable_and_more'),
        ('masterdata', '0005_alter_supplier_supplier_type'),
        ('sales', '0005_salesorderitem_customer_model_remark_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=100, unique=True)),
                ('external_invoice_no', models.CharField(blank=True, max_length=100)),
                ('invoice_date', models.DateField()),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已开票'), ('voided', '已作废')], default='draft', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('remark', models.TextField(blank=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='masterdata.customer')),
                ('reconciliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_invoices', to='finance.reconciliation')),
            ],
            options={
                'db_table': 'customer_invoices',
            },
        ),
        migrations.CreateModel(
            name='CustomerInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.customerinvoice')),
                ('reconciliation_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_invoice_items', to='finance.reconciliationitem')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='sales.salesorder')),
            ],
            options={
                'db_table': 'customer_invoice_items',
            },
        ),
        migrations.AddIndex(
            model_name='customerinvoice',
            index=models.Index(fields=['customer', 'status', 'invoice_date'], name='customer_in_custome_919945_idx'),
        ),
        migrations.AddIndex(
            model_name='customerinvoice',
            index=models.Index(fields=['reconciliation', 'status'], name='customer_in_reconci_4bc846_idx'),
        ),
        migrations.AddIndex(
            model_name='customerinvoice',
            index=models.Index(fields=['external_invoice_no'], name='customer_in_externa_f29077_idx'),
        ),
        migrations.AddIndex(
            model_name='customerinvoiceitem',
            index=models.Index(fields=['customer_invoice', 'line_no'], name='customer_in_custome_da44d1_idx'),
        ),
        migrations.AddIndex(
            model_name='customerinvoiceitem',
            index=models.Index(fields=['sales_order'], name='customer_in_sales_o_c03111_idx'),
        ),
        migrations.AddIndex(
            model_name='customerinvoiceitem',
            index=models.Index(fields=['reconciliation_item'], name='customer_in_reconci_cd3d92_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerinvoiceitem',
            constraint=models.UniqueConstraint(fields=('customer_invoice', 'line_no'), name='uq_customer_invoice_item_line'),
        ),
    ]
