from django.urls import path

from .views import (
    InventoryBatchListView,
    InventoryBatchDetailView,
    InventoryBatchExportView,
    InventoryExportView,
    InventoryDetailView,
    InventoryListView,
    InitialInventoryImportTemplateView,
    InitialInventoryCancelView,
    InitialInventoryConfirmView,
    InitialInventoryImportView,
    InventoryTransactionExportView,
    InventoryTransactionDetailView,
    InventoryTransactionListView,
    LocationTransferConfirmView,
    LocationTransferCreateView,
    LocationTransferDetailView,
    LocationTransferExportView,
    LocationTransferListView,
    LocationTransferPrintView,
    StockCountConfirmView,
    StockCountCreateView,
    StockCountDetailView,
    StockCountExportView,
    StockCountItemCreateView,
    StockCountListView,
    StockCountPrintView,
    WarehouseLocationCreateView,
    WarehouseLocationDetailView,
    WarehouseLocationExportView,
    WarehouseLocationImportTemplateView,
    WarehouseLocationImportView,
    WarehouseLocationListView,
    WarehouseLocationUpdateView,
)

app_name = "inventory"

urlpatterns = [
    path("locations/", WarehouseLocationListView.as_view(), name="warehouse_location_list"),
    path("locations/export/", WarehouseLocationExportView.as_view(), name="warehouse_location_export"),
    path("locations/new/", WarehouseLocationCreateView.as_view(), name="warehouse_location_create"),
    path("locations/<int:pk>/", WarehouseLocationDetailView.as_view(), name="warehouse_location_detail"),
    path("locations/<int:pk>/edit/", WarehouseLocationUpdateView.as_view(), name="warehouse_location_edit"),
    path("locations/import-template/", WarehouseLocationImportTemplateView.as_view(), name="warehouse_location_import_template"),
    path("locations/import/", WarehouseLocationImportView.as_view(), name="warehouse_location_import"),
    path("", InventoryListView.as_view(), name="inventory_list"),
    path("export/", InventoryExportView.as_view(), name="inventory_export"),
    path("<int:pk>/", InventoryDetailView.as_view(), name="inventory_detail"),
    path("initial-import-template/", InitialInventoryImportTemplateView.as_view(), name="initial_inventory_import_template"),
    path("initial-import/", InitialInventoryImportView.as_view(), name="initial_inventory_import"),
    path("initial-import/<int:pk>/confirm/", InitialInventoryConfirmView.as_view(), name="initial_inventory_confirm"),
    path("initial-import/<int:pk>/cancel/", InitialInventoryCancelView.as_view(), name="initial_inventory_cancel"),
    path("batches/", InventoryBatchListView.as_view(), name="inventory_batch_list"),
    path("batches/export/", InventoryBatchExportView.as_view(), name="inventory_batch_export"),
    path("batches/<int:pk>/", InventoryBatchDetailView.as_view(), name="inventory_batch_detail"),
    path("transactions/", InventoryTransactionListView.as_view(), name="inventory_transaction_list"),
    path("transactions/export/", InventoryTransactionExportView.as_view(), name="inventory_transaction_export"),
    path("transactions/<int:pk>/", InventoryTransactionDetailView.as_view(), name="inventory_transaction_detail"),
    path("transfers/", LocationTransferListView.as_view(), name="location_transfer_list"),
    path("transfers/export/", LocationTransferExportView.as_view(), name="location_transfer_export"),
    path("transfers/new/", LocationTransferCreateView.as_view(), name="location_transfer_create"),
    path("transfers/<int:pk>/", LocationTransferDetailView.as_view(), name="location_transfer_detail"),
    path("transfers/<int:pk>/print/", LocationTransferPrintView.as_view(), name="location_transfer_print"),
    path("transfers/<int:pk>/confirm/", LocationTransferConfirmView.as_view(), name="location_transfer_confirm"),
    path("stock-counts/", StockCountListView.as_view(), name="stock_count_list"),
    path("stock-counts/export/", StockCountExportView.as_view(), name="stock_count_export"),
    path("stock-counts/new/", StockCountCreateView.as_view(), name="stock_count_create"),
    path("stock-counts/<int:pk>/", StockCountDetailView.as_view(), name="stock_count_detail"),
    path("stock-counts/<int:pk>/print/", StockCountPrintView.as_view(), name="stock_count_print"),
    path("stock-counts/<int:pk>/items/new/", StockCountItemCreateView.as_view(), name="stock_count_item_create"),
    path("stock-counts/<int:pk>/confirm/", StockCountConfirmView.as_view(), name="stock_count_confirm"),
]
