# Generated by Django 6.0.6 on 2026-06-08 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bom', '0001_initial'),
        ('inventory', '0001_initial'),
        ('masterdata', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionMaterialRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_no', models.CharField(max_length=100, unique=True)),
                ('requisition_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_confirm', '待确认'), ('issued', '已出库'), ('voided', '已作废')], default='draft', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'production_material_requisitions',
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_order_no', models.CharField(max_length=100, unique=True)),
                ('production_qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('received_qty', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('locked_bom_version', models.CharField(max_length=40)),
                ('label_requirements', models.JSONField(blank=True, default=dict)),
                ('packaging_requirements', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', '待生产'), ('in_progress', '生产中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=32)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_finish_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('remark', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('finished_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.material')),
                ('locked_bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bom.bom')),
                ('sales_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='sales.salesorderitem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'production_orders',
            },
        ),
        migrations.CreateModel(
            name='ProductionMaterialRequisitionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('required_qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('issued_qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('adjust_reason', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorybatch')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouselocation')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.material')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.productionmaterialrequisition')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.productionorder')),
            ],
            options={
                'db_table': 'production_material_requisition_items',
            },
        ),
        migrations.AddField(
            model_name='productionmaterialrequisition',
            name='production_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_requisitions', to='production.productionorder'),
        ),
        migrations.CreateModel(
            name='ProductionReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_receipt_no', models.CharField(max_length=100, unique=True)),
                ('receipt_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_confirm', '待确认'), ('received', '已入库'), ('voided', '已作废')], default='draft', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='production.productionorder')),
            ],
            options={
                'db_table': 'production_receipts',
            },
        ),
        migrations.CreateModel(
            name='ProductionReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('receipt_qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('batch_no', models.CharField(blank=True, max_length=100)),
                ('quality_status', models.CharField(choices=[('qualified', '合格'), ('pending', '待检'), ('defective', '不良')], default='qualified', max_length=24)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorybatch')),
                ('finished_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.material')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouselocation')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.productionorder')),
                ('production_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.productionreceipt')),
            ],
            options={
                'db_table': 'production_receipt_items',
            },
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['sales_order_item', 'status'], name='production__sales_o_bce781_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['finished_material', 'status'], name='production__finishe_6a310d_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['status', 'created_at'], name='production__status_99b2d3_idx'),
        ),
        migrations.AddIndex(
            model_name='productionmaterialrequisitionitem',
            index=models.Index(fields=['production_order', 'material'], name='production__product_ecea1e_idx'),
        ),
        migrations.AddIndex(
            model_name='productionmaterialrequisitionitem',
            index=models.Index(fields=['batch', 'location'], name='production__batch_i_82ef6d_idx'),
        ),
        migrations.AddConstraint(
            model_name='productionmaterialrequisitionitem',
            constraint=models.UniqueConstraint(fields=('requisition', 'line_no'), name='uq_production_requisition_line'),
        ),
        migrations.AddIndex(
            model_name='productionmaterialrequisition',
            index=models.Index(fields=['production_order', 'status'], name='production__product_f0cac4_idx'),
        ),
        migrations.AddIndex(
            model_name='productionmaterialrequisition',
            index=models.Index(fields=['requisition_date'], name='production__requisi_994259_idx'),
        ),
        migrations.AddIndex(
            model_name='productionreceipt',
            index=models.Index(fields=['production_order', 'status'], name='production__product_4666a5_idx'),
        ),
        migrations.AddIndex(
            model_name='productionreceipt',
            index=models.Index(fields=['receipt_date'], name='production__receipt_e58a24_idx'),
        ),
        migrations.AddIndex(
            model_name='productionreceiptitem',
            index=models.Index(fields=['production_order', 'finished_material'], name='production__product_4cbbde_idx'),
        ),
        migrations.AddIndex(
            model_name='productionreceiptitem',
            index=models.Index(fields=['batch'], name='production__batch_i_221ebe_idx'),
        ),
        migrations.AddConstraint(
            model_name='productionreceiptitem',
            constraint=models.UniqueConstraint(fields=('production_receipt', 'line_no'), name='uq_production_receipt_line'),
        ),
    ]
