# Generated by Django 6.0.6 on 2026-06-08 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('masterdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_return_no', models.CharField(max_length=100, unique=True)),
                ('return_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_approval', '待审核'), ('rejected', '已驳回'), ('confirmed', '已确认'), ('shipped', '已退货出库'), ('voided', '已作废')], default='draft', max_length=32)),
                ('return_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'supplier_returns',
            },
        ),
        migrations.CreateModel(
            name='SupplierReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=6, max_digits=14)),
                ('return_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('return_reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'supplier_return_items',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order_no', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_approval', '待审核'), ('rejected', '已驳回'), ('approved', '已通过'), ('partial_received', '部分到货'), ('received', '已到货'), ('closed', '已关闭'), ('voided', '已作废')], default='draft', max_length=32)),
                ('order_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='masterdata.supplier')),
            ],
            options={
                'db_table': 'purchase_orders',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('order_qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('received_qty', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=6, max_digits=14)),
                ('line_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('needed_date', models.DateField(blank=True, null=True)),
                ('line_status', models.CharField(choices=[('open', '未到货'), ('partial_received', '部分到货'), ('received', '已到货'), ('closed', '已关闭')], default='open', max_length=32)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.material')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.purchaseorder')),
            ],
            options={
                'db_table': 'purchase_order_items',
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_receipt_no', models.CharField(max_length=100, unique=True)),
                ('receipt_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_approval', '待审核'), ('pending_receive', '待入库'), ('partial_received', '部分入库'), ('received', '已入库'), ('voided', '已作废')], default='draft', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='purchase.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.supplier')),
            ],
            options={
                'db_table': 'purchase_receipts',
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('accepted_qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('rejected_qty', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=6, max_digits=14)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorybatch')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouselocation')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.material')),
                ('purchase_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchase.purchaseorderitem')),
                ('purchase_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.purchasereceipt')),
            ],
            options={
                'db_table': 'purchase_receipt_items',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_request_no', models.CharField(max_length=100, unique=True)),
                ('source_type', models.CharField(choices=[('manual', '人工'), ('shortage', '欠料'), ('low_stock', '低库存')], default='manual', max_length=24)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_approval', '待审核'), ('rejected', '已驳回'), ('approved', '已通过'), ('closed', '已关闭'), ('voided', '已作废')], default='draft', max_length=32)),
                ('needed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(blank=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'purchase_requests',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('request_qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('needed_date', models.DateField(blank=True, null=True)),
                ('line_status', models.CharField(choices=[('open', '未下单'), ('ordered', '已下单'), ('partial_ordered', '部分下单'), ('closed', '已关闭')], default='open', max_length=32)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.material')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.purchaserequest')),
            ],
            options={
                'db_table': 'purchase_request_items',
            },
        ),
    ]
