# Generated by Django 6.0.6 on 2026-06-08 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('masterdata', '0001_initial'),
        ('purchase', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequestitem',
            name='source_sales_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.salesorderitem'),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='source_shortage_alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.shortagealert'),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='suggested_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.supplier'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='purchase_request_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchase.purchaserequestitem'),
        ),
        migrations.AddField(
            model_name='supplierreturn',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierreturn',
            name='purchase_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchase.purchasereceipt'),
        ),
        migrations.AddField(
            model_name='supplierreturn',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.supplier'),
        ),
        migrations.AddField(
            model_name='supplierreturnitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorybatch'),
        ),
        migrations.AddField(
            model_name='supplierreturnitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouselocation'),
        ),
        migrations.AddField(
            model_name='supplierreturnitem',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.material'),
        ),
        migrations.AddField(
            model_name='supplierreturnitem',
            name='purchase_receipt_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchase.purchasereceiptitem'),
        ),
        migrations.AddField(
            model_name='supplierreturnitem',
            name='supplier_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.supplierreturn'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier', 'status'], name='purchase_or_supplie_8a71bd_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['order_date'], name='purchase_or_order_d_409199_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereceipt',
            index=models.Index(fields=['supplier', 'status'], name='purchase_re_supplie_fa874e_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereceipt',
            index=models.Index(fields=['receipt_date'], name='purchase_re_receipt_9c07d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchasereceiptitem',
            constraint=models.UniqueConstraint(fields=('purchase_receipt', 'purchase_order_item', 'material'), name='uq_purchase_receipt_item'),
        ),
        migrations.AddIndex(
            model_name='purchaserequestitem',
            index=models.Index(fields=['material', 'line_status'], name='purchase_re_materia_388d7b_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequestitem',
            index=models.Index(fields=['source_shortage_alert'], name='purchase_re_source__ea9dd9_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequestitem',
            constraint=models.UniqueConstraint(fields=('purchase_request', 'line_no'), name='uq_purchase_request_line'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderitem',
            index=models.Index(fields=['purchase_order', 'line_status'], name='purchase_or_purchas_01dbed_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderitem',
            index=models.Index(fields=['material'], name='purchase_or_materia_8a3942_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'line_no'), name='uq_purchase_order_line'),
        ),
        migrations.AddConstraint(
            model_name='supplierreturnitem',
            constraint=models.UniqueConstraint(fields=('supplier_return', 'material', 'purchase_receipt_item'), name='uq_supplier_return_item'),
        ),
    ]
