from django.urls import path

from .views import (
    ProductionMaterialRequisitionConfirmView,
    ProductionMaterialRequisitionDetailView,
    ProductionMaterialRequisitionExportView,
    ProductionMaterialRequisitionImportTemplateView,
    ProductionMaterialRequisitionImportView,
    ProductionMaterialRequisitionListView,
    ProductionMaterialRequisitionPrintView,
    ProductionMaterialRequisitionUpdateView,
    ProductionOrderCancelView,
    ProductionOrderCreateView,
    ProductionOrderCreateReceiptView,
    ProductionOrderCreateRequisitionView,
    ProductionOrderDetailView,
    ProductionOrderExportView,
    ProductionOrderImportTemplateView,
    ProductionOrderImportView,
    ProductionOrderListView,
    ProductionOrderPrintView,
    ProductionOrderUpdateView,
    ProductionReceiptConfirmView,
    ProductionReceiptDetailView,
    ProductionReceiptExportView,
    ProductionReceiptImportTemplateView,
    ProductionReceiptImportView,
    ProductionReceiptListView,
    ProductionReceiptPrintView,
    ProductionReceiptUpdateView,
)

app_name = "production"

urlpatterns = [
    path("orders/", ProductionOrderListView.as_view(), name="production_order_list"),
    path("orders/export/", ProductionOrderExportView.as_view(), name="production_order_export"),
    path("orders/import-template/", ProductionOrderImportTemplateView.as_view(), name="production_order_import_template"),
    path("orders/import/", ProductionOrderImportView.as_view(), name="production_order_import"),
    path("orders/new/", ProductionOrderCreateView.as_view(), name="production_order_create"),
    path("orders/<int:pk>/", ProductionOrderDetailView.as_view(), name="production_order_detail"),
    path("orders/<int:pk>/edit/", ProductionOrderUpdateView.as_view(), name="production_order_edit"),
    path("orders/<int:pk>/print/", ProductionOrderPrintView.as_view(), name="production_order_print"),
    path("orders/<int:pk>/cancel/", ProductionOrderCancelView.as_view(), name="production_order_cancel"),
    path("orders/<int:pk>/create-requisition/", ProductionOrderCreateRequisitionView.as_view(), name="production_order_create_requisition"),
    path("orders/<int:pk>/create-receipt/", ProductionOrderCreateReceiptView.as_view(), name="production_order_create_receipt"),
    path("requisitions/", ProductionMaterialRequisitionListView.as_view(), name="material_requisition_list"),
    path("requisitions/export/", ProductionMaterialRequisitionExportView.as_view(), name="material_requisition_export"),
    path("requisitions/import-template/", ProductionMaterialRequisitionImportTemplateView.as_view(), name="material_requisition_import_template"),
    path("requisitions/import/", ProductionMaterialRequisitionImportView.as_view(), name="material_requisition_import"),
    path("requisitions/<int:pk>/", ProductionMaterialRequisitionDetailView.as_view(), name="material_requisition_detail"),
    path("requisitions/<int:pk>/edit/", ProductionMaterialRequisitionUpdateView.as_view(), name="material_requisition_edit"),
    path("requisitions/<int:pk>/print/", ProductionMaterialRequisitionPrintView.as_view(), name="material_requisition_print"),
    path("requisitions/<int:pk>/confirm/", ProductionMaterialRequisitionConfirmView.as_view(), name="material_requisition_confirm"),
    path("receipts/", ProductionReceiptListView.as_view(), name="production_receipt_list"),
    path("receipts/export/", ProductionReceiptExportView.as_view(), name="production_receipt_export"),
    path("receipts/import-template/", ProductionReceiptImportTemplateView.as_view(), name="production_receipt_import_template"),
    path("receipts/import/", ProductionReceiptImportView.as_view(), name="production_receipt_import"),
    path("receipts/<int:pk>/", ProductionReceiptDetailView.as_view(), name="production_receipt_detail"),
    path("receipts/<int:pk>/edit/", ProductionReceiptUpdateView.as_view(), name="production_receipt_edit"),
    path("receipts/<int:pk>/print/", ProductionReceiptPrintView.as_view(), name="production_receipt_print"),
    path("receipts/<int:pk>/confirm/", ProductionReceiptConfirmView.as_view(), name="production_receipt_confirm"),
]
