# Generated by Django 6.0.6 on 2026-06-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='security_level',
            field=models.CharField(choices=[('L1', '普通账号'), ('L2', '敏感账号'), ('L3', '部门管理员'), ('L4', '系统管理员')], default='L1', max_length=8),
        ),
    ]
