# Generated by Django 6.0.6 on 2026-06-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_security_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, db_table='role_permissions', related_name='roles', to='accounts.permission'),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, db_table='user_roles', related_name='users', to='accounts.role'),
        ),
    ]
