from django.urls import path

from .views import (
    CustomerCreditBalanceApplyView,
    CustomerCreditBalanceDetailView,
    CustomerCreditBalanceExportView,
    CustomerCreditBalanceListView,
    CustomerCreditBalancePrintView,
    CustomerReceiptConfirmView,
    CustomerReceiptCreateView,
    CustomerReceiptDetailView,
    CustomerReceiptUpdateView,
    CustomerReceiptExportView,
    CustomerReceiptImportTemplateView,
    CustomerReceiptImportView,
    CustomerReceiptListView,
    CustomerReceiptPrintView,
    CustomerReceiptReverseView,
    CustomerReceiptVoidView,
    ExpenseRecordConfirmView,
    ExpenseRecordCreateView,
    ExpenseRecordDetailView,
    ExpenseRecordListView,
    ExpenseRecordVoidView,
    OperationsDashboardView,
    OpeningPayableCreateView,
    OpeningPayableDetailView,
    OpeningPayableListView,
    OpeningPayableVoidView,
    OpeningReceivableCreateView,
    OpeningReceivableDetailView,
    OpeningReceivableListView,
    OpeningReceivableVoidView,
    ReconciliationExportView,
    ReconciliationListView,
    SupplierCreditBalanceApplyView,
    SupplierCreditBalanceDetailView,
    SupplierCreditBalanceExportView,
    SupplierCreditBalanceListView,
    SupplierCreditBalancePrintView,
    SupplierPaymentConfirmView,
    SupplierPaymentCreateView,
    SupplierPaymentDetailView,
    SupplierPaymentUpdateView,
    SupplierPaymentExportView,
    SupplierPaymentImportTemplateView,
    SupplierPaymentImportView,
    SupplierPaymentListView,
    SupplierPaymentPrintView,
    SupplierPaymentReverseView,
    SupplierPaymentVoidView,
    ReconciliationConfirmView,
    ReconciliationCreateView,
    ReconciliationDetailView,
    ReconciliationPrintView,
    ReconciliationVoidView,
)

app_name = "finance"

urlpatterns = [
    path("operations/", OperationsDashboardView.as_view(), name="operations_dashboard"),
    path("customer-receipts/", CustomerReceiptListView.as_view(), name="customer_receipt_list"),
    path("customer-receipts/export/", CustomerReceiptExportView.as_view(), name="customer_receipt_export"),
    path("customer-receipts/import-template/", CustomerReceiptImportTemplateView.as_view(), name="customer_receipt_import_template"),
    path("customer-receipts/import/", CustomerReceiptImportView.as_view(), name="customer_receipt_import"),
    path("customer-receipts/new/", CustomerReceiptCreateView.as_view(), name="customer_receipt_create"),
    path("customer-receipts/<int:pk>/", CustomerReceiptDetailView.as_view(), name="customer_receipt_detail"),
    path("customer-receipts/<int:pk>/edit/", CustomerReceiptUpdateView.as_view(), name="customer_receipt_edit"),
    path("customer-receipts/<int:pk>/print/", CustomerReceiptPrintView.as_view(), name="customer_receipt_print"),
    path("customer-receipts/<int:pk>/confirm/", CustomerReceiptConfirmView.as_view(), name="customer_receipt_confirm"),
    path("customer-receipts/<int:pk>/reverse/", CustomerReceiptReverseView.as_view(), name="customer_receipt_reverse"),
    path("customer-receipts/<int:pk>/void/", CustomerReceiptVoidView.as_view(), name="customer_receipt_void"),
    path("supplier-payments/", SupplierPaymentListView.as_view(), name="supplier_payment_list"),
    path("supplier-payments/export/", SupplierPaymentExportView.as_view(), name="supplier_payment_export"),
    path("supplier-payments/import-template/", SupplierPaymentImportTemplateView.as_view(), name="supplier_payment_import_template"),
    path("supplier-payments/import/", SupplierPaymentImportView.as_view(), name="supplier_payment_import"),
    path("supplier-payments/new/", SupplierPaymentCreateView.as_view(), name="supplier_payment_create"),
    path("supplier-payments/<int:pk>/", SupplierPaymentDetailView.as_view(), name="supplier_payment_detail"),
    path("supplier-payments/<int:pk>/edit/", SupplierPaymentUpdateView.as_view(), name="supplier_payment_edit"),
    path("supplier-payments/<int:pk>/print/", SupplierPaymentPrintView.as_view(), name="supplier_payment_print"),
    path("supplier-payments/<int:pk>/confirm/", SupplierPaymentConfirmView.as_view(), name="supplier_payment_confirm"),
    path("supplier-payments/<int:pk>/reverse/", SupplierPaymentReverseView.as_view(), name="supplier_payment_reverse"),
    path("supplier-payments/<int:pk>/void/", SupplierPaymentVoidView.as_view(), name="supplier_payment_void"),
    path("opening-receivables/", OpeningReceivableListView.as_view(), name="opening_receivable_list"),
    path("opening-receivables/new/", OpeningReceivableCreateView.as_view(), name="opening_receivable_create"),
    path("opening-receivables/<int:pk>/", OpeningReceivableDetailView.as_view(), name="opening_receivable_detail"),
    path("opening-receivables/<int:pk>/void/", OpeningReceivableVoidView.as_view(), name="opening_receivable_void"),
    path("opening-payables/", OpeningPayableListView.as_view(), name="opening_payable_list"),
    path("opening-payables/new/", OpeningPayableCreateView.as_view(), name="opening_payable_create"),
    path("opening-payables/<int:pk>/", OpeningPayableDetailView.as_view(), name="opening_payable_detail"),
    path("opening-payables/<int:pk>/void/", OpeningPayableVoidView.as_view(), name="opening_payable_void"),
    path("expenses/", ExpenseRecordListView.as_view(), name="expense_record_list"),
    path("expenses/new/", ExpenseRecordCreateView.as_view(), name="expense_record_create"),
    path("expenses/<int:pk>/", ExpenseRecordDetailView.as_view(), name="expense_record_detail"),
    path("expenses/<int:pk>/confirm/", ExpenseRecordConfirmView.as_view(), name="expense_record_confirm"),
    path("expenses/<int:pk>/void/", ExpenseRecordVoidView.as_view(), name="expense_record_void"),
    path("customer-balances/", CustomerCreditBalanceListView.as_view(), name="customer_credit_balance_list"),
    path("customer-balances/export/", CustomerCreditBalanceExportView.as_view(), name="customer_credit_balance_export"),
    path("customer-balances/<int:pk>/", CustomerCreditBalanceDetailView.as_view(), name="customer_credit_balance_detail"),
    path("customer-balances/<int:pk>/print/", CustomerCreditBalancePrintView.as_view(), name="customer_credit_balance_print"),
    path("customer-balances/<int:pk>/apply/", CustomerCreditBalanceApplyView.as_view(), name="customer_credit_balance_apply"),
    path("supplier-balances/", SupplierCreditBalanceListView.as_view(), name="supplier_credit_balance_list"),
    path("supplier-balances/export/", SupplierCreditBalanceExportView.as_view(), name="supplier_credit_balance_export"),
    path("supplier-balances/<int:pk>/", SupplierCreditBalanceDetailView.as_view(), name="supplier_credit_balance_detail"),
    path("supplier-balances/<int:pk>/print/", SupplierCreditBalancePrintView.as_view(), name="supplier_credit_balance_print"),
    path("supplier-balances/<int:pk>/apply/", SupplierCreditBalanceApplyView.as_view(), name="supplier_credit_balance_apply"),
    path("reconciliations/", ReconciliationListView.as_view(), name="reconciliation_list"),
    path("reconciliations/export/", ReconciliationExportView.as_view(), name="reconciliation_export"),
    path("reconciliations/new/", ReconciliationCreateView.as_view(), name="reconciliation_create"),
    path("reconciliations/<int:pk>/", ReconciliationDetailView.as_view(), name="reconciliation_detail"),
    path("reconciliations/<int:pk>/print/", ReconciliationPrintView.as_view(), name="reconciliation_print"),
    path("reconciliations/<int:pk>/confirm/", ReconciliationConfirmView.as_view(), name="reconciliation_confirm"),
    path("reconciliations/<int:pk>/void/", ReconciliationVoidView.as_view(), name="reconciliation_void"),
]
