# Generated by Django 6.0.6 on 2026-06-08 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.CharField(max_length=80, unique=True)),
                ('location_name', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=16)),
                ('remark', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'warehouse_locations',
            },
        ),
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=100, unique=True)),
                ('inventory_type', models.CharField(choices=[('available', '可用'), ('defective', '不良'), ('pending', '待处理'), ('sample', '样品')], default='available', max_length=24)),
                ('received_at', models.DateTimeField()),
                ('initial_qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('remaining_qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('batch_status', models.CharField(choices=[('in_stock', '在库'), ('frozen', '冻结'), ('voided', '作废'), ('used_up', '已用完')], default='in_stock', max_length=24)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_batches', to='masterdata.material')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouselocation')),
            ],
            options={
                'db_table': 'inventory_batches',
            },
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_count_no', models.CharField(max_length=100, unique=True)),
                ('scope_type', models.CharField(max_length=40)),
                ('scope_value', models.CharField(blank=True, max_length=200)),
                ('snapshot_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('counting', '盘点中'), ('pending_approval', '待审核'), ('approved_pending_adjustment', '待调整'), ('adjusted', '已调整'), ('voided', '已作废')], default='draft', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stock_counts',
            },
        ),
        migrations.CreateModel(
            name='LocationTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_no', models.CharField(max_length=100, unique=True)),
                ('transfer_qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('voided', '已作废')], default='draft', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorybatch')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.material')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='inventory.warehouselocation')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='inventory.warehouselocation')),
            ],
            options={
                'db_table': 'location_transfers',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_type', models.CharField(choices=[('available', '可用'), ('defective', '不良'), ('pending', '待处理'), ('sample', '样品')], max_length=24)),
                ('qty', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_summaries', to='masterdata.material')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouselocation')),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='StockCountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('counted_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('difference_qty', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('difference_reason', models.TextField(blank=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorybatch')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.material')),
                ('stock_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockcount')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouselocation')),
            ],
            options={
                'db_table': 'stock_count_items',
                'constraints': [models.UniqueConstraint(fields=('stock_count', 'material', 'batch', 'location'), name='uq_stock_count_item_scope')],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(max_length=100, unique=True)),
                ('transaction_type', models.CharField(choices=[('purchase_in', '采购入库'), ('sales_out', '销售出库'), ('production_issue', '生产领料'), ('production_receipt', '生产入库'), ('sample_out', '借样出库'), ('sample_return_in', '借样归还入库'), ('customer_return_in', '客户退货入库'), ('supplier_return_out', '供应商退货出库'), ('sample_to_sales', '借样转销售'), ('location_transfer', '库位移库'), ('stock_adjustment', '盘点调整')], max_length=40)),
                ('qty_delta', models.DecimalField(decimal_places=4, max_digits=14)),
                ('source_doc_type', models.CharField(max_length=80)),
                ('source_doc_id', models.PositiveBigIntegerField()),
                ('source_doc_no', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorybatch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.material')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouselocation')),
            ],
            options={
                'db_table': 'inventory_transactions',
                'indexes': [models.Index(fields=['material', 'created_at'], name='inventory_t_materia_3e4e91_idx'), models.Index(fields=['source_doc_type', 'source_doc_id'], name='inventory_t_source__60497f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['material', 'location', 'received_at', 'batch_no'], name='inventory_b_materia_7ec40e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['batch_status', 'inventory_type'], name='inventory_b_batch_s_bf2e88_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('material', 'location', 'inventory_type'), name='uq_inventory_material_location_type'),
        ),
    ]
