# Generated by Django 6.0.6 on 2026-06-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase_in', '采购入库'), ('sales_out', '销售出库'), ('production_issue', '生产领料'), ('production_receipt', '生产入库'), ('sample_out', '借样出库'), ('sample_return_in', '借样归还入库'), ('customer_return_in', '客户退货入库'), ('supplier_return_out', '供应商退货出库'), ('sample_to_sales', '借样转销售'), ('location_transfer', '库位移库'), ('stock_adjustment', '盘点调整'), ('initial_stock', '期初库存')], max_length=40),
        ),
    ]
