# Generated by Django 6.0.6 on 2026-06-08 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('customer_no', models.CharField(max_length=80, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=120)),
                ('settlement_method', models.CharField(blank=True, max_length=80)),
                ('contact_phone_encrypted', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用'), ('blacklist', '黑名单')], default='active', max_length=16)),
                ('remark', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sales_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('receiver_name', models.CharField(max_length=120)),
                ('receiver_phone_encrypted', models.TextField(blank=True)),
                ('address_encrypted', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='masterdata.customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_addresses',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('material_code', models.CharField(max_length=80, unique=True)),
                ('material_name', models.CharField(max_length=200)),
                ('material_type', models.CharField(choices=[('finished', '成品'), ('raw', '原料'), ('part', '配件'), ('packaging', '包装材料'), ('other', '其他')], max_length=24)),
                ('spec', models.CharField(blank=True, max_length=200)),
                ('base_unit', models.CharField(max_length=32)),
                ('qty_precision', models.PositiveSmallIntegerField(default=0)),
                ('min_stock_qty', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('latest_purchase_price', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=16)),
                ('remark', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'materials',
            },
        ),
        migrations.CreateModel(
            name='CustomerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('customer_product_no', models.CharField(max_length=80)),
                ('customer_product_name', models.CharField(max_length=200)),
                ('default_sale_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('label_requirements', models.JSONField(blank=True, default=dict)),
                ('packaging_requirements', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='masterdata.customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('finished_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.material')),
            ],
            options={
                'db_table': 'customer_products',
            },
        ),
        migrations.CreateModel(
            name='MaterialUnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('source_unit', models.CharField(max_length=32)),
                ('target_unit', models.CharField(max_length=32)),
                ('ratio', models.DecimalField(decimal_places=8, max_digits=18)),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_conversions', to='masterdata.material')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'material_unit_conversions',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('supplier_no', models.CharField(max_length=80, unique=True)),
                ('supplier_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('contact_phone_encrypted', models.TextField(blank=True)),
                ('supplier_type', models.CharField(blank=True, max_length=80)),
                ('payment_method', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用'), ('blacklist', '黑名单')], default='active', max_length=16)),
                ('remark', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'suppliers',
            },
        ),
        migrations.CreateModel(
            name='MaterialSupplierPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('purchase_price', models.DecimalField(decimal_places=6, max_digits=14)),
                ('currency', models.CharField(default='CNY', max_length=12)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_prices', to='masterdata.material')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_prices', to='masterdata.supplier')),
            ],
            options={
                'db_table': 'material_supplier_prices',
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_name'], name='customers_custome_147306_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['sales_owner', 'status'], name='customers_sales_o_5ecabc_idx'),
        ),
        migrations.AddIndex(
            model_name='customeraddress',
            index=models.Index(fields=['customer', 'status'], name='customer_ad_custome_21389f_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['material_type', 'status'], name='materials_materia_0d9a28_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['material_name'], name='materials_materia_4ae4ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerproduct',
            constraint=models.UniqueConstraint(fields=('customer', 'customer_product_no'), name='uq_customer_product_no'),
        ),
        migrations.AddConstraint(
            model_name='materialunitconversion',
            constraint=models.UniqueConstraint(fields=('material', 'source_unit', 'target_unit'), name='uq_material_unit_conversion'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['supplier_name'], name='suppliers_supplie_2362cc_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['status'], name='suppliers_status_e3c425_idx'),
        ),
        migrations.AddIndex(
            model_name='materialsupplierprice',
            index=models.Index(fields=['material', 'supplier', 'status'], name='material_su_materia_e5c839_idx'),
        ),
        migrations.AddIndex(
            model_name='materialsupplierprice',
            index=models.Index(fields=['is_default', 'status'], name='material_su_is_defa_6557cd_idx'),
        ),
    ]
