# Generated by Django 6.0.6 on 2026-06-08 07:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='address_type',
            field=models.CharField(choices=[('shipping', '收货地址'), ('return', '退货地址'), ('sample', '样品地址')], default='shipping', max_length=24),
        ),
        migrations.AddIndex(
            model_name='customeraddress',
            index=models.Index(fields=['customer', 'address_type', 'status'], name='customer_ad_custome_f47b6c_idx'),
        ),
    ]
