# Generated by Django 6.0.6 on 2026-07-04 04:38

from django.db import migrations, models


SETTLEMENT_METHOD_NORMALIZE_MAP = {
    "cash": "现结",
    "现款": "现结",
    "monthly": "月结",
    "month": "月结",
    "monthly30": "月结30天",
    "月结30": "月结30天",
    "月结 30": "月结30天",
    "monthly60": "月结60天",
    "月结60": "月结60天",
    "月结 60": "月结60天",
    "prepaid": "预付",
    "prepay": "预付",
    "payment_before_shipment": "款到发货",
    "before_shipment": "款到发货",
    "cod": "货到付款",
    "cash_on_delivery": "货到付款",
    "after_reconciliation": "对账后付款",
    "reconciliation": "对账后付款",
}


def normalize_settlement_methods(apps, schema_editor):
    Customer = apps.get_model("masterdata", "Customer")
    for old_value, new_value in SETTLEMENT_METHOD_NORMALIZE_MAP.items():
        Customer.objects.filter(settlement_method=old_value).update(settlement_method=new_value)


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_customeraddress_address_type_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_settlement_methods, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customer',
            name='settlement_method',
            field=models.CharField(blank=True, choices=[('现结', '现结'), ('月结', '月结'), ('月结30天', '月结30天'), ('月结60天', '月结60天'), ('预付', '预付'), ('款到发货', '款到发货'), ('货到付款', '货到付款'), ('对账后付款', '对账后付款')], max_length=80),
        ),
    ]
