# Generated by Django 6.0.6 on 2026-07-04 06:08

from django.db import migrations, models


PAYMENT_METHOD_NORMALIZE_MAP = {
    "cash": "现金",
    "现金付款": "现金",
    "transfer": "转账",
    "银行转账": "转账",
    "bank_transfer": "转账",
    "check": "支票",
    "cheque": "支票",
    "现结": "现付",
    "现款": "现付",
    "pay_now": "现付",
    "monthly": "月结",
    "month": "月结",
    "monthly30": "月结30天",
    "月结30": "月结30天",
    "月结 30": "月结30天",
    "monthly60": "月结60天",
    "月结60": "月结60天",
    "月结 60": "月结60天",
    "prepaid": "预付",
    "prepay": "预付",
    "cod": "货到付款",
    "cash_on_delivery": "货到付款",
    "after_reconciliation": "对账后付款",
    "reconciliation": "对账后付款",
    "other": "其他",
}


def normalize_supplier_payment_methods(apps, schema_editor):
    Supplier = apps.get_model("masterdata", "Supplier")
    for old_value, new_value in PAYMENT_METHOD_NORMALIZE_MAP.items():
        Supplier.objects.filter(payment_method=old_value).update(payment_method=new_value)


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_alter_customer_settlement_method'),
    ]

    operations = [
        migrations.RunPython(normalize_supplier_payment_methods, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='supplier',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('现金', '现金'), ('转账', '转账'), ('支票', '支票'), ('现付', '现付'), ('月结', '月结'), ('月结30天', '月结30天'), ('月结60天', '月结60天'), ('预付', '预付'), ('货到付款', '货到付款'), ('对账后付款', '对账后付款'), ('其他', '其他')], max_length=80),
        ),
    ]
