# Generated by Django 6.0.6 on 2026-07-04 06:15

from django.db import migrations, models


SUPPLIER_TYPE_NORMALIZE_MAP = {
    "raw": "原料",
    "主料": "原料",
    "原料供应商": "原料",
    "auxiliary": "辅料",
    "辅材": "辅料",
    "辅料供应商": "辅料",
    "part": "配件",
    "parts": "配件",
    "零件": "配件",
    "配件供应商": "配件",
    "packaging": "包装",
    "包材": "包装",
    "包装材料": "包装",
    "包装供应商": "包装",
    "outsourcing": "外协加工",
    "outsource": "外协加工",
    "外协": "外协加工",
    "加工": "外协加工",
    "代工": "外协加工",
    "transport": "运输",
    "logistics": "运输",
    "物流": "运输",
    "运输供应商": "运输",
    "equipment": "设备",
    "设备供应商": "设备",
    "service": "服务",
    "服务供应商": "服务",
    "other": "其他",
}


def normalize_supplier_types(apps, schema_editor):
    Supplier = apps.get_model("masterdata", "Supplier")
    for old_value, new_value in SUPPLIER_TYPE_NORMALIZE_MAP.items():
        Supplier.objects.filter(supplier_type=old_value).update(supplier_type=new_value)


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_alter_supplier_payment_method'),
    ]

    operations = [
        migrations.RunPython(normalize_supplier_types, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(blank=True, choices=[('原料', '原料'), ('辅料', '辅料'), ('配件', '配件'), ('包装', '包装'), ('外协加工', '外协加工'), ('运输', '运输'), ('设备', '设备'), ('服务', '服务'), ('其他', '其他')], max_length=80),
        ),
    ]
