"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")
DJANGO_ENV = os.getenv("DJANGO_ENV", "development").lower()
IS_PRODUCTION = DJANGO_ENV in {"production", "prod"}


def _path_from_env(env_name: str, default: Path) -> Path:
    configured = os.getenv(env_name)
    if not configured:
        return default
    path = Path(configured)
    if path.is_absolute():
        return path
    return BASE_DIR / path


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    if IS_PRODUCTION:
        raise RuntimeError("DJANGO_SECRET_KEY must be set when DJANGO_ENV=production")
    SECRET_KEY = "dev-only-insecure-secret-key"
elif IS_PRODUCTION and (
    SECRET_KEY.startswith("django-insecure-")
    or SECRET_KEY.startswith("replace-")
    or len(SECRET_KEY) < 50
    or len(set(SECRET_KEY)) < 8
):
    raise RuntimeError("DJANGO_SECRET_KEY is too weak for production")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "false").lower() == "true"
if IS_PRODUCTION and DEBUG:
    raise RuntimeError("DJANGO_DEBUG must be false when DJANGO_ENV=production")

ALLOWED_HOSTS = [host for host in os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,testserver").split(",") if host]
if IS_PRODUCTION and (
    not ALLOWED_HOSTS
    or any(host in {"*", "localhost", "127.0.0.1", "testserver"} for host in ALLOWED_HOSTS)
):
    raise RuntimeError("DJANGO_ALLOWED_HOSTS must contain only real production hostnames when DJANGO_ENV=production")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'masterdata',
    'bom',
    'inventory',
    'sales',
    'purchase',
    'production',
    'finance',
    'approvals',
    'notifications',
    'files',
    'system',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'accounts.middleware.UserSessionTrackingMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL_ENGINE = os.getenv("DB_ENGINE", "sqlite")
if IS_PRODUCTION and DATABASE_URL_ENGINE != "postgres":
    raise RuntimeError("DB_ENGINE must be postgres when DJANGO_ENV=production")

if DATABASE_URL_ENGINE == "postgres":
    POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD", "")
    if IS_PRODUCTION and not POSTGRES_PASSWORD:
        raise RuntimeError("POSTGRES_PASSWORD must be set when DJANGO_ENV=production")
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB", "erp_db"),
            "USER": os.getenv("POSTGRES_USER", "erp_app"),
            "PASSWORD": POSTGRES_PASSWORD,
            "HOST": os.getenv("POSTGRES_HOST", "localhost"),
            "PORT": os.getenv("POSTGRES_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Hong_Kong'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = _path_from_env("DJANGO_STATIC_ROOT", BASE_DIR / "staticfiles")

MEDIA_URL = "media/"
MEDIA_ROOT = _path_from_env("ERP_ATTACHMENT_DIR", BASE_DIR / "media")
ERP_BACKUP_DIR = _path_from_env("ERP_BACKUP_DIR", BASE_DIR / "backups")
ERP_MAX_CSV_IMPORT_SIZE = int(os.getenv("ERP_MAX_CSV_IMPORT_SIZE", str(5 * 1024 * 1024)))
ERP_MAX_CSV_IMPORT_ROWS = int(os.getenv("ERP_MAX_CSV_IMPORT_ROWS", "5000"))
ERP_ATTACHMENT_SCAN_COMMAND = os.getenv("ERP_ATTACHMENT_SCAN_COMMAND", "")
ERP_ATTACHMENT_SCAN_TIMEOUT = int(os.getenv("ERP_ATTACHMENT_SCAN_TIMEOUT", "30"))
ERP_ATTACHMENT_SCAN_RISK_ACCEPTED_BY = os.getenv("ERP_ATTACHMENT_SCAN_RISK_ACCEPTED_BY", "")
ERP_INTRANET_HTTP_RISK_ACCEPTED_BY = os.getenv("ERP_INTRANET_HTTP_RISK_ACCEPTED_BY", "")
ERP_RELEASE_GATE_REPORT_FILE = _path_from_env("ERP_RELEASE_GATE_REPORT_FILE", BASE_DIR / "docs" / "latest-release-gate-report.md")
ERP_RELEASE_GATE_MAX_AGE_HOURS = int(os.getenv("ERP_RELEASE_GATE_MAX_AGE_HOURS", "24"))
ERP_PRELAUNCH_BACKUP_MAX_AGE_HOURS = int(os.getenv("ERP_PRELAUNCH_BACKUP_MAX_AGE_HOURS", "24"))
ERP_PRELAUNCH_BACKUP_VERIFY_MAX_AGE_HOURS = int(os.getenv("ERP_PRELAUNCH_BACKUP_VERIFY_MAX_AGE_HOURS", "24"))
ERP_PRELAUNCH_RESTORE_DRILL_MAX_AGE_HOURS = int(os.getenv("ERP_PRELAUNCH_RESTORE_DRILL_MAX_AGE_HOURS", "168"))
ERP_PRELAUNCH_EVENT_PROCESS_MAX_AGE_MINUTES = int(os.getenv("ERP_PRELAUNCH_EVENT_PROCESS_MAX_AGE_MINUTES", "30"))
ERP_PENDING_EVENT_MAX_RETRIES = int(os.getenv("ERP_PENDING_EVENT_MAX_RETRIES", "3"))
ERP_PENDING_EVENT_RETRY_BASE_MINUTES = int(os.getenv("ERP_PENDING_EVENT_RETRY_BASE_MINUTES", "5"))
ERP_PENDING_EVENT_RUNNING_TIMEOUT_MINUTES = int(os.getenv("ERP_PENDING_EVENT_RUNNING_TIMEOUT_MINUTES", "30"))
ERP_BACKGROUND_JOB_RUNNING_TIMEOUT_MINUTES = int(os.getenv("ERP_BACKGROUND_JOB_RUNNING_TIMEOUT_MINUTES", "120"))

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "accounts.User"

LOGIN_URL = os.getenv("DJANGO_LOGIN_URL", "/login/")
LOGIN_REDIRECT_URL = os.getenv("DJANGO_LOGIN_REDIRECT_URL", "/")
SESSION_COOKIE_AGE = int(os.getenv("DJANGO_SESSION_COOKIE_AGE", str(8 * 60 * 60)))
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_SECURE = os.getenv("DJANGO_SESSION_COOKIE_SECURE", "true" if IS_PRODUCTION else "false").lower() == "true"
CSRF_COOKIE_SECURE = os.getenv("DJANGO_CSRF_COOKIE_SECURE", "true" if IS_PRODUCTION else "false").lower() == "true"
CSRF_TRUSTED_ORIGINS = [
    origin
    for origin in os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin
]
SECURE_SSL_REDIRECT = os.getenv("DJANGO_SECURE_SSL_REDIRECT", "true" if IS_PRODUCTION else "false").lower() == "true"
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_HSTS_SECONDS = int(os.getenv("DJANGO_SECURE_HSTS_SECONDS", "31536000" if IS_PRODUCTION else "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = (
    os.getenv("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", "true" if IS_PRODUCTION else "false").lower() == "true"
)
SECURE_HSTS_PRELOAD = os.getenv("DJANGO_SECURE_HSTS_PRELOAD", "false").lower() == "true"

LOG_DIR = _path_from_env("DJANGO_LOG_DIR", BASE_DIR / "logs")
LOG_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "[{asctime}] {levelname} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
        "file": {
            "class": "system.logging_handlers.SafeRotatingFileHandler",
            "filename": LOG_DIR / "erp.log",
            "maxBytes": 10 * 1024 * 1024,
            "backupCount": 10,
            "encoding": "utf-8",
            "formatter": "standard",
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
    },
    "loggers": {
        "django.server": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
    },
}
