# Generated by Django 6.0.6 on 2026-06-08 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bom_no', models.CharField(max_length=100)),
                ('bom_version', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_approval', '待审核'), ('rejected', '已驳回'), ('enabled', '已启用'), ('disabled', '已停用'), ('voided', '已作废')], default='draft', max_length=32)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('remark', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('finished_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='masterdata.material')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'boms',
            },
        ),
        migrations.CreateModel(
            name='BomItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('usage_qty', models.DecimalField(decimal_places=6, max_digits=14)),
                ('usage_unit', models.CharField(max_length=32)),
                ('loss_rate', models.DecimalField(decimal_places=6, default=0, max_digits=7)),
                ('is_required', models.BooleanField(default=True)),
                ('remark', models.TextField(blank=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bom.bom')),
                ('component_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_bom_items', to='masterdata.material')),
            ],
            options={
                'db_table': 'bom_items',
            },
        ),
        migrations.AddIndex(
            model_name='bom',
            index=models.Index(fields=['finished_material', 'status'], name='boms_finishe_99011b_idx'),
        ),
        migrations.AddIndex(
            model_name='bom',
            index=models.Index(fields=['status', 'created_at'], name='boms_status_62a684_idx'),
        ),
        migrations.AddConstraint(
            model_name='bom',
            constraint=models.UniqueConstraint(fields=('bom_no',), name='uq_bom_no'),
        ),
        migrations.AddConstraint(
            model_name='bom',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['rejected', 'voided']), _negated=True), fields=('finished_material', 'bom_version'), name='uq_active_bom_version'),
        ),
        migrations.AddIndex(
            model_name='bomitem',
            index=models.Index(fields=['component_material'], name='bom_items_compone_97c074_idx'),
        ),
        migrations.AddConstraint(
            model_name='bomitem',
            constraint=models.UniqueConstraint(fields=('bom', 'line_no'), name='uq_bom_item_line'),
        ),
    ]
