# Generated by Django 6.0.6 on 2026-06-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='base_qty',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=14),
        ),
        migrations.AddField(
            model_name='bom',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bom',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bom',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
