# Generated by Django 6.0.6 on 2026-06-08 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_no', models.CharField(max_length=100, unique=True)),
                ('source_doc_type', models.CharField(max_length=80)),
                ('source_doc_id', models.PositiveBigIntegerField()),
                ('source_doc_no', models.CharField(blank=True, max_length=100)),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('checksum_sha256', models.CharField(blank=True, max_length=128)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', '有效'), ('deleted', '已删除')], default='active', max_length=16)),
                ('scan_status', models.CharField(choices=[('not_required', '无需扫描'), ('pending', '待扫描'), ('passed', '通过'), ('failed', '失败')], default='not_required', max_length=24)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('delete_reason', models.TextField(blank=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attachments',
            },
        ),
        migrations.CreateModel(
            name='AttachmentAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='files.attachment')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attachment_access_logs',
            },
        ),
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_no', models.CharField(max_length=100, unique=True)),
                ('module', models.CharField(max_length=80)),
                ('filter_json', models.JSONField(blank=True, default=dict)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'export_logs',
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.CharField(max_length=100, unique=True)),
                ('template_type', models.CharField(max_length=80)),
                ('template_version', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('pending', '待执行'), ('validating', '校验中'), ('importing', '导入中'), ('success', '成功'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=16)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('error_summary', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('source_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='files.attachment')),
            ],
            options={
                'db_table': 'import_jobs',
            },
        ),
        migrations.CreateModel(
            name='InitializationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.CharField(max_length=100, unique=True)),
                ('template_type', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('validating', '校验中'), ('pending_confirm', '待确认'), ('importing', '导入中'), ('success', '成功'), ('failed', '失败'), ('cancelled', '已取消')], default='draft', max_length=24)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('error_summary', models.JSONField(blank=True, default=dict)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_initialization_jobs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('source_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='files.attachment')),
            ],
            options={
                'db_table': 'initialization_jobs',
            },
        ),
        migrations.CreateModel(
            name='PrintLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_no', models.CharField(max_length=100, unique=True)),
                ('template_type', models.CharField(max_length=80)),
                ('source_doc_type', models.CharField(max_length=80)),
                ('source_doc_id', models.PositiveBigIntegerField()),
                ('source_doc_no', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'print_logs',
            },
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['source_doc_type', 'source_doc_id', 'status'], name='attachments_source__ba3673_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['uploaded_by', 'uploaded_at'], name='attachments_uploade_c2e865_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['checksum_sha256'], name='attachments_checksu_66352f_idx'),
        ),
        migrations.AddIndex(
            model_name='attachmentaccesslog',
            index=models.Index(fields=['attachment', 'created_at'], name='attachment__attachm_e4de3e_idx'),
        ),
        migrations.AddIndex(
            model_name='attachmentaccesslog',
            index=models.Index(fields=['operator', 'created_at'], name='attachment__operato_1f58c6_idx'),
        ),
        migrations.AddIndex(
            model_name='exportlog',
            index=models.Index(fields=['module', 'created_at'], name='export_logs_module_5cde4b_idx'),
        ),
        migrations.AddIndex(
            model_name='exportlog',
            index=models.Index(fields=['exported_by', 'created_at'], name='export_logs_exporte_e5663b_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['template_type', 'status'], name='import_jobs_templat_d1d828_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['status', 'created_at'], name='import_jobs_status_aedc42_idx'),
        ),
        migrations.AddIndex(
            model_name='initializationjob',
            index=models.Index(fields=['template_type', 'status'], name='initializat_templat_b90a48_idx'),
        ),
        migrations.AddIndex(
            model_name='initializationjob',
            index=models.Index(fields=['status', 'created_at'], name='initializat_status_3250e6_idx'),
        ),
        migrations.AddIndex(
            model_name='printlog',
            index=models.Index(fields=['template_type', 'created_at'], name='print_logs_templat_30064c_idx'),
        ),
        migrations.AddIndex(
            model_name='printlog',
            index=models.Index(fields=['source_doc_type', 'source_doc_id'], name='print_logs_source__45e49e_idx'),
        ),
        migrations.AddIndex(
            model_name='printlog',
            index=models.Index(fields=['printed_by', 'created_at'], name='print_logs_printed_b69763_idx'),
        ),
    ]
