# Generated by Django 6.0.6 on 2026-06-08 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_no', models.CharField(max_length=100, unique=True)),
                ('approval_type', models.CharField(max_length=80)),
                ('source_object_id', models.PositiveBigIntegerField()),
                ('source_doc_type', models.CharField(max_length=80)),
                ('source_no', models.CharField(max_length=100)),
                ('source_title', models.CharField(max_length=200)),
                ('source_summary', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回'), ('transferred', '已转交'), ('withdrawn', '已撤回')], default='pending', max_length=24)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('remark', models.TextField(blank=True)),
                ('current_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pending_approvals', to=settings.AUTH_USER_MODEL)),
                ('source_content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'approvals',
            },
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submit', '提交'), ('approve', '同意'), ('reject', '驳回'), ('transfer', '转交'), ('add_approver', '加签'), ('return_to_edit', '退回修改'), ('withdraw', '撤回'), ('auto_skip', '自动跳过')], max_length=32)),
                ('comment', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='approvals.approval')),
                ('from_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('to_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'approval_logs',
            },
        ),
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=80)),
                ('condition_json', models.JSONField(blank=True, default=dict)),
                ('level_no', models.PositiveIntegerField()),
                ('allow_auto_skip_same_user', models.BooleanField(default=True)),
                ('require_second_verify', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(blank=True)),
                ('approver_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.role')),
                ('approver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'approval_rules',
            },
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['current_approver', 'status', 'submitted_at'], name='approvals_current_a6d8f4_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['source_doc_type', 'source_object_id'], name='approvals_source__52ee35_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['approval_type', 'status'], name='approvals_approva_2458e7_idx'),
        ),
        migrations.AddIndex(
            model_name='approvallog',
            index=models.Index(fields=['approval', 'created_at'], name='approval_lo_approva_9b4b81_idx'),
        ),
        migrations.AddIndex(
            model_name='approvallog',
            index=models.Index(fields=['operator', 'created_at'], name='approval_lo_operato_a214ef_idx'),
        ),
        migrations.AddIndex(
            model_name='approvallog',
            index=models.Index(fields=['action', 'created_at'], name='approval_lo_action_59f5a0_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrule',
            index=models.Index(fields=['doc_type', 'status', 'level_no'], name='approval_ru_doc_typ_359465_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrule',
            index=models.Index(fields=['approver_user', 'status'], name='approval_ru_approve_8fe138_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrule',
            index=models.Index(fields=['approver_role', 'status'], name='approval_ru_approve_c2df7b_idx'),
        ),
    ]
