# Generated by Django 6.0.6 on 2026-06-08 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_no', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('urgent', '紧急'), ('normal', '普通'), ('info', '通知')], default='normal', max_length=16)),
                ('status', models.CharField(choices=[('unread', '未读'), ('read', '已读'), ('processed', '已处理'), ('snoozed', '稍后提醒'), ('closed', '已关闭')], default='unread', max_length=16)),
                ('source_doc_type', models.CharField(blank=True, max_length=80)),
                ('source_doc_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('source_doc_no', models.CharField(blank=True, max_length=100)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('suggested_action', models.CharField(blank=True, max_length=200)),
                ('remind_at', models.DateTimeField(blank=True, null=True)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_messages',
                'indexes': [models.Index(fields=['receiver', 'status', 'level', 'created_at'], name='system_mess_receive_569ab8_idx'), models.Index(fields=['source_doc_type', 'source_doc_id'], name='system_mess_source__33e0c7_idx'), models.Index(fields=['remind_at', 'status'], name='system_mess_remind__96f18f_idx')],
            },
        ),
    ]
