from django.urls import path

from .views import (
    CustomerCreateView,
    CustomerAddressCreateView,
    CustomerAddressImportTemplateView,
    CustomerAddressImportView,
    CustomerAddressUpdateView,
    CustomerDetailView,
    CustomerExportView,
    CustomerImportTemplateView,
    CustomerImportView,
    CustomerListView,
    CustomerUpdateView,
    CustomerProductExportView,
    CustomerProductImportTemplateView,
    CustomerProductImportView,
    CustomerProductListView,
    CustomerProductCreateView,
    CustomerProductDetailView,
    CustomerProductUpdateView,
    MaterialCreateView,
    MaterialExportView,
    MaterialImportTemplateView,
    MaterialImportView,
    MaterialDetailView,
    MaterialSupplierPriceImportTemplateView,
    MaterialSupplierPriceImportView,
    MaterialSupplierPriceCreateView,
    MaterialSupplierPriceUpdateView,
    MaterialListView,
    MaterialUnitConversionImportTemplateView,
    MaterialUnitConversionImportView,
    MaterialUnitConversionCreateView,
    MaterialUnitConversionUpdateView,
    MaterialUpdateView,
    SupplierCreateView,
    SupplierDetailView,
    SupplierExportView,
    SupplierImportTemplateView,
    SupplierImportView,
    SupplierListView,
    SupplierUpdateView,
)

app_name = "masterdata"

urlpatterns = [
    path("materials/", MaterialListView.as_view(), name="material_list"),
    path("materials/export/", MaterialExportView.as_view(), name="material_export"),
    path("materials/import-template/", MaterialImportTemplateView.as_view(), name="material_import_template"),
    path("materials/import/", MaterialImportView.as_view(), name="material_import"),
    path(
        "materials/unit-conversions/import-template/",
        MaterialUnitConversionImportTemplateView.as_view(),
        name="material_unit_conversion_import_template",
    ),
    path(
        "materials/unit-conversions/import/",
        MaterialUnitConversionImportView.as_view(),
        name="material_unit_conversion_import",
    ),
    path(
        "materials/supplier-prices/import-template/",
        MaterialSupplierPriceImportTemplateView.as_view(),
        name="material_supplier_price_import_template",
    ),
    path(
        "materials/supplier-prices/import/",
        MaterialSupplierPriceImportView.as_view(),
        name="material_supplier_price_import",
    ),
    path("materials/new/", MaterialCreateView.as_view(), name="material_create"),
    path("materials/<int:pk>/", MaterialDetailView.as_view(), name="material_detail"),
    path("materials/<int:pk>/edit/", MaterialUpdateView.as_view(), name="material_edit"),
    path("materials/<int:material_pk>/unit-conversions/new/", MaterialUnitConversionCreateView.as_view(), name="material_unit_conversion_create"),
    path(
        "materials/unit-conversions/<int:pk>/edit/",
        MaterialUnitConversionUpdateView.as_view(),
        name="material_unit_conversion_edit",
    ),
    path("materials/<int:material_pk>/supplier-prices/new/", MaterialSupplierPriceCreateView.as_view(), name="material_supplier_price_create"),
    path(
        "materials/supplier-prices/<int:pk>/edit/",
        MaterialSupplierPriceUpdateView.as_view(),
        name="material_supplier_price_edit",
    ),
    path("customers/", CustomerListView.as_view(), name="customer_list"),
    path("customers/export/", CustomerExportView.as_view(), name="customer_export"),
    path("customers/import-template/", CustomerImportTemplateView.as_view(), name="customer_import_template"),
    path("customers/import/", CustomerImportView.as_view(), name="customer_import"),
    path(
        "customers/addresses/import-template/",
        CustomerAddressImportTemplateView.as_view(),
        name="customer_address_import_template",
    ),
    path("customers/addresses/import/", CustomerAddressImportView.as_view(), name="customer_address_import"),
    path("customers/new/", CustomerCreateView.as_view(), name="customer_create"),
    path("customers/<int:pk>/", CustomerDetailView.as_view(), name="customer_detail"),
    path("customers/<int:pk>/edit/", CustomerUpdateView.as_view(), name="customer_edit"),
    path("customers/<int:customer_pk>/products/new/", CustomerProductCreateView.as_view(), name="customer_product_create"),
    path("customers/<int:customer_pk>/addresses/new/", CustomerAddressCreateView.as_view(), name="customer_address_create"),
    path("customers/addresses/<int:pk>/edit/", CustomerAddressUpdateView.as_view(), name="customer_address_edit"),
    path("customer-products/", CustomerProductListView.as_view(), name="customer_product_list"),
    path("customer-products/export/", CustomerProductExportView.as_view(), name="customer_product_export"),
    path("customer-products/<int:pk>/", CustomerProductDetailView.as_view(), name="customer_product_detail"),
    path("customer-products/<int:pk>/edit/", CustomerProductUpdateView.as_view(), name="customer_product_edit"),
    path(
        "customer-products/import-template/",
        CustomerProductImportTemplateView.as_view(),
        name="customer_product_import_template",
    ),
    path("customer-products/import/", CustomerProductImportView.as_view(), name="customer_product_import"),
    path("suppliers/", SupplierListView.as_view(), name="supplier_list"),
    path("suppliers/export/", SupplierExportView.as_view(), name="supplier_export"),
    path("suppliers/import-template/", SupplierImportTemplateView.as_view(), name="supplier_import_template"),
    path("suppliers/import/", SupplierImportView.as_view(), name="supplier_import"),
    path("suppliers/new/", SupplierCreateView.as_view(), name="supplier_create"),
    path("suppliers/<int:pk>/", SupplierDetailView.as_view(), name="supplier_detail"),
    path("suppliers/<int:pk>/edit/", SupplierUpdateView.as_view(), name="supplier_edit"),
]
