# Generated by Django 6.0.6 on 2026-06-08 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bom', '0001_initial'),
        ('inventory', '0001_initial'),
        ('masterdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_order_no', models.CharField(max_length=100, unique=True)),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_approval', '待审核'), ('rejected', '已驳回'), ('pending_bom', '待 BOM 处理'), ('confirmed', '已确认'), ('in_production', '生产中'), ('shipped', '已发货'), ('completed', '已完成'), ('voided', '已作废')], default='draft', max_length=32)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('contract_attachment_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('remark', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='masterdata.customer')),
                ('customer_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.customeraddress')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_orders',
            },
        ),
        migrations.CreateModel(
            name='CustomerReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_no', models.CharField(max_length=100, unique=True)),
                ('return_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_approval', '待审核'), ('rejected', '已驳回'), ('confirmed', '已确认'), ('received', '已收货'), ('voided', '已作废')], default='draft', max_length=32)),
                ('return_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remark', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.customer')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.salesorder')),
            ],
            options={
                'db_table': 'customer_returns',
            },
        ),
        migrations.CreateModel(
            name='SalesOrderChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_reason', models.TextField()),
                ('before_snapshot', models.JSONField(default=dict)),
                ('after_snapshot', models.JSONField(default=dict)),
                ('approval_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='sales.salesorder')),
            ],
            options={
                'db_table': 'sales_order_change_logs',
            },
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('order_qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('shipped_qty', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('line_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('locked_bom_version', models.CharField(blank=True, max_length=40)),
                ('line_status', models.CharField(choices=[('draft', '草稿'), ('pending_approval', '待审核'), ('confirmed', '已确认'), ('in_production', '生产中'), ('shipped', '已发货'), ('completed', '已完成')], default='draft', max_length=32)),
                ('inventory_check_status', models.CharField(choices=[('unchecked', '未检查'), ('sufficient', '库存充足'), ('pending_bom', '待 BOM 处理'), ('shortage', '欠料'), ('kitted', '已齐套')], default='unchecked', max_length=32)),
                ('customer_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.customerproduct')),
                ('finished_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.material')),
                ('locked_bom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bom.bom')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesorder')),
            ],
            options={
                'db_table': 'sales_order_items',
            },
        ),
        migrations.CreateModel(
            name='CustomerReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('return_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('inventory_type', models.CharField(default='available', max_length=24)),
                ('return_reason', models.TextField(blank=True)),
                ('customer_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.customerreturn')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouselocation')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.material')),
                ('sales_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.salesorderitem')),
            ],
            options={
                'db_table': 'customer_return_items',
            },
        ),
        migrations.CreateModel(
            name='SalesShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_no', models.CharField(max_length=100, unique=True)),
                ('shipment_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_confirm', '待确认'), ('shipped', '已出库'), ('voided', '已作废')], default='draft', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.customer')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='sales.salesorder')),
            ],
            options={
                'db_table': 'sales_shipments',
            },
        ),
        migrations.CreateModel(
            name='SalesShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorybatch')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouselocation')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.material')),
                ('sales_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.salesorderitem')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesshipment')),
            ],
            options={
                'db_table': 'sales_shipment_items',
            },
        ),
        migrations.CreateModel(
            name='SampleLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_loan_no', models.CharField(max_length=100, unique=True)),
                ('loan_date', models.DateField()),
                ('expected_return_date', models.DateField()),
                ('status', models.CharField(choices=[('pending_approval', '待审核'), ('out', '已出库'), ('part_returned', '部分归还'), ('returned', '已归还'), ('part_sold', '部分转销售'), ('sold', '已转销售'), ('voided', '已作废')], default='pending_approval', max_length=32)),
                ('is_overdue', models.BooleanField(default=False)),
                ('overdue_days', models.PositiveIntegerField(default=0)),
                ('overdue_status', models.CharField(choices=[('none', '未逾期'), ('due_soon', '即将到期'), ('overdue', '已逾期'), ('closed', '已关闭')], default='none', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.customer')),
            ],
            options={
                'db_table': 'sample_loans',
            },
        ),
        migrations.CreateModel(
            name='SampleLoanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('loan_qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('returned_qty', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('sold_qty', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('line_status', models.CharField(choices=[('out', '已出库'), ('part_returned', '部分归还'), ('returned', '已归还'), ('part_sold', '部分转销售'), ('sold', '已转销售'), ('voided', '已作废')], default='out', max_length=32)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorybatch')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouselocation')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.material')),
                ('sample_loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sampleloan')),
            ],
            options={
                'db_table': 'sample_loan_items',
            },
        ),
        migrations.CreateModel(
            name='SampleLoanReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_return_no', models.CharField(max_length=100, unique=True)),
                ('return_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_confirm', '待确认'), ('received', '已入库'), ('voided', '已作废')], default='draft', max_length=32)),
                ('remark', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.customer')),
                ('sample_loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.sampleloan')),
            ],
            options={
                'db_table': 'sample_loan_returns',
            },
        ),
        migrations.CreateModel(
            name='SampleLoanReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('inventory_type', models.CharField(default='available', max_length=24)),
                ('sample_condition', models.CharField(choices=[('good', '完好'), ('damaged', '损坏'), ('pending_check', '待检'), ('missing_part', '缺件')], default='good', max_length=32)),
                ('remark', models.TextField(blank=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouselocation')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.material')),
                ('sample_loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.sampleloan')),
                ('sample_loan_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.sampleloanitem')),
                ('sample_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sampleloanreturn')),
            ],
            options={
                'db_table': 'sample_loan_return_items',
            },
        ),
        migrations.CreateModel(
            name='ShortageAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortage_no', models.CharField(max_length=100, unique=True)),
                ('required_qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('available_qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('shortage_qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('is_required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('unprocessed', '未处理'), ('purchase_requested', '已生成采购需求'), ('partial_received', '部分到货'), ('kitted', '已齐套'), ('closed', '已关闭')], default='unprocessed', max_length=32)),
                ('purchase_request_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('closed_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.material')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortage_alerts', to='sales.salesorder')),
                ('sales_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortage_alerts', to='sales.salesorderitem')),
            ],
            options={
                'db_table': 'shortage_alerts',
            },
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['customer', 'status'], name='sales_order_custome_c0587e_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['delivery_date'], name='sales_order_deliver_35fd00_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['created_at'], name='sales_order_created_bf3c26_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorderchangelog',
            index=models.Index(fields=['sales_order', 'changed_at'], name='sales_order_sales_o_6a5e0c_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorderitem',
            index=models.Index(fields=['sales_order', 'line_status'], name='sales_order_sales_o_f131b5_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorderitem',
            index=models.Index(fields=['finished_material'], name='sales_order_finishe_5bdb01_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesorderitem',
            constraint=models.UniqueConstraint(fields=('sales_order', 'customer_product'), name='uq_sales_order_customer_product'),
        ),
        migrations.AddConstraint(
            model_name='salesorderitem',
            constraint=models.UniqueConstraint(fields=('sales_order', 'line_no'), name='uq_sales_order_line'),
        ),
        migrations.AddConstraint(
            model_name='customerreturnitem',
            constraint=models.UniqueConstraint(fields=('customer_return', 'sales_order_item', 'material'), name='uq_customer_return_item'),
        ),
        migrations.AddConstraint(
            model_name='salesshipmentitem',
            constraint=models.UniqueConstraint(fields=('shipment', 'sales_order_item', 'batch'), name='uq_sales_shipment_item'),
        ),
        migrations.AddIndex(
            model_name='sampleloan',
            index=models.Index(fields=['customer', 'status'], name='sample_loan_custome_db02a0_idx'),
        ),
        migrations.AddIndex(
            model_name='sampleloan',
            index=models.Index(fields=['overdue_status', 'expected_return_date'], name='sample_loan_overdue_e33f45_idx'),
        ),
        migrations.AddConstraint(
            model_name='sampleloanitem',
            constraint=models.UniqueConstraint(fields=('sample_loan', 'line_no'), name='uq_sample_loan_line'),
        ),
        migrations.AddConstraint(
            model_name='sampleloanreturnitem',
            constraint=models.UniqueConstraint(fields=('sample_return', 'sample_loan_item', 'location'), name='uq_sample_return_item'),
        ),
        migrations.AddIndex(
            model_name='shortagealert',
            index=models.Index(fields=['status', 'material'], name='shortage_al_status_3aeb7a_idx'),
        ),
        migrations.AddIndex(
            model_name='shortagealert',
            index=models.Index(fields=['sales_order_item', 'status'], name='shortage_al_sales_o_cfd6a6_idx'),
        ),
    ]
