# Generated by Django 6.0.6 on 2026-06-08 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shortagealert',
            name='purchase_request_id',
            field=models.ForeignKey(blank=True, db_column='purchase_request_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shortage_alerts', to='purchase.purchaserequest'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameField(
                    model_name='shortagealert',
                    old_name='purchase_request_id',
                    new_name='purchase_request',
                ),
            ],
        ),
    ]
