# Generated by Django 6.0.6 on 2026-06-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_shortagealert_purchase_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='customer_contract_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='settlement_method',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='salesshipment',
            name='customer_address_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salesshipment',
            name='customer_contact_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='salesshipment',
            name='customer_contact_phone',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='salesshipment',
            name='customer_contract_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='salesshipment',
            name='settlement_method',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
