# Generated by Django 6.0.6 on 2026-07-12 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_alter_supplier_supplier_type'),
        ('sales', '0004_alter_salesorder_settlement_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='customer_model_remark',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='customer_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.customerproduct'),
        ),
    ]
