# Generated by Codex on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_salesorderitem_customer_model_remark_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sampleloanitem",
            name="remark",
            field=models.TextField(blank=True),
        ),
    ]
